-- Add translations for Events page content in all languages
INSERT INTO translations (key, language_code, text, category) VALUES
-- Title and subtitle translations (additional languages)
('events.title', 'es', 'La Experiencia de Regata Completa', 'events_page'),
('events.title', 'pl', 'Pełne Doświadczenie Regat', 'events_page'),
('events.title', 'he', 'חוויית תחרות השיט המלאה', 'events_page'),

('events.subtitle', 'es', 'De principiante a campeón en un día. Experimenta auténticas regatas de yates en el Lago de Garda con instrucción profesional, regatas competitivas y reconocimiento oficial de tu logro.', 'events_page'),
('events.subtitle', 'pl', 'Od początkującego do mistrza w jeden dzień. Doświadcz autentycznych regat jachtowych na Jeziorze Garda z profesjonalnym instruktażem, wyścigami konkursowymi i oficjalnym uznaniem Twojego osiągnięcia.', 'events_page'),
('events.subtitle', 'he', 'ממתחיל לאלוף ביום אחד. חווה תחרויות יאכטות אותנטיות באגם גארדה עם הדרכה מקצועית, מרוצים תחרותיים והכרה רשמית בהישג שלך.', 'events_page'),

-- Complete Experience section
('events.complete_experience', 'es', 'La Experiencia de Regata Completa', 'events_page'),
('events.complete_experience', 'it', 'L''Esperienza di Regata Completa', 'events_page'),
('events.complete_experience', 'de', 'Das komplette Regatta-Erlebnis', 'events_page'),
('events.complete_experience', 'fr', 'L''Expérience Complète de Régate', 'events_page'),
('events.complete_experience', 'pl', 'Pełne Doświadczenie Regat', 'events_page'),
('events.complete_experience', 'he', 'חוויית תחרות השיט המלאה', 'events_page'),

('events.beginner_to_champion', 'es', 'De principiante a campeón en un día. Experimenta auténticas regatas de yates en el Lago de Garda con instrucción profesional, regatas competitivas y reconocimiento oficial de tu logro.', 'events_page'),
('events.beginner_to_champion', 'it', 'Da principiante a campione in un giorno. Vivi l''autentica vela da regata sul Lago di Garda con istruzione professionale, regate competitive e riconoscimento ufficiale del tuo successo.', 'events_page'),
('events.beginner_to_champion', 'de', 'Vom Anfänger zum Champion an einem Tag. Erleben Sie authentischen Segelrennsport am Gardasee mit professionellem Unterricht, Wettkampfregatten und offizieller Anerkennung Ihrer Leistung.', 'events_page'),
('events.beginner_to_champion', 'fr', 'De débutant à champion en une journée. Vivez l''authentique course de voilier sur le lac de Garde avec une instruction professionnelle, des régates compétitives et une reconnaissance officielle de votre réussite.', 'events_page'),
('events.beginner_to_champion', 'pl', 'Od początkującego do mistrza w jeden dzień. Doświadcz autentycznych regat jachtowych na Jeziorze Garda z profesjonalnym instruktażem, wyścigami konkursowymi i oficjalnym uznaniem Twojego osiągnięcia.', 'events_page'),
('events.beginner_to_champion', 'he', 'ממתחיל לאלוף ביום אחד. חווה תחרויות יאכטות אותנטיות באגם גארדה עם הדרכה מקצועית, מרוצים תחרותיים והכרה רשמית בהישג שלך.', 'events_page'),

-- Tabs translations (additional languages)
('events.tabs.overview', 'es', 'Visión general', 'events_page'),
('events.tabs.overview', 'pl', 'Przegląd', 'events_page'),
('events.tabs.overview', 'he', 'סקירה כללית', 'events_page'),

('events.tabs.schedule', 'es', 'Horario', 'events_page'),
('events.tabs.schedule', 'pl', 'Harmonogram', 'events_page'),
('events.tabs.schedule', 'he', 'לוח זמנים', 'events_page'),

('events.tabs.gallery', 'es', 'Galería', 'events_page'),
('events.tabs.gallery', 'pl', 'Galeria', 'events_page'),
('events.tabs.gallery', 'he', 'גלריה', 'events_page'),

('events.tabs.weather', 'es', 'Clima', 'events_page'),
('events.tabs.weather', 'pl', 'Pogoda', 'events_page'),
('events.tabs.weather', 'he', 'מזג אוויר', 'events_page'),

('events.tabs.equipment', 'es', 'Equipamiento', 'events_page'),
('events.tabs.equipment', 'pl', 'Sprzęt', 'events_page'),
('events.tabs.equipment', 'he', 'ציוד', 'events_page'),

('events.tabs.faq', 'es', 'Preguntas frecuentes', 'events_page'),
('events.tabs.faq', 'pl', 'FAQ', 'events_page'),
('events.tabs.faq', 'he', 'שאלות נפוצות', 'events_page'),

-- Overview section translations
('events.overview.what_makes_special', 'es', 'Qué Hace Nuestra Experiencia Especial', 'events_page'),
('events.overview.what_makes_special', 'it', 'Cosa Rende Speciale la Nostra Esperienza', 'events_page'),
('events.overview.what_makes_special', 'pl', 'Co Sprawia, że Nasze Doświadczenie Jest Wyjątkowe', 'events_page'),
('events.overview.what_makes_special', 'he', 'מה הופך את החוויה שלנו למיוחדת', 'events_page'),

('events.overview.professional_instruction', 'es', 'Instrucción Profesional', 'events_page'),
('events.overview.professional_instruction', 'pl', 'Profesjonalny Instruktaż', 'events_page'),
('events.overview.professional_instruction', 'he', 'הדרכה מקצועית', 'events_page'),

('events.overview.professional_instruction_desc', 'es', 'Aprende de profesionales certificados de vela con años de experiencia en regatas en el Lago de Garda.', 'events_page'),
('events.overview.professional_instruction_desc', 'it', 'Impara da professionisti della vela certificati con anni di esperienza di regata sul Lago di Garda.', 'events_page'),
('events.overview.professional_instruction_desc', 'pl', 'Ucz się od certyfikowanych profesjonalistów żeglarskich z wieloletnim doświadczeniem w regatach na Jeziorze Garda.', 'events_page'),
('events.overview.professional_instruction_desc', 'he', 'למד ממדריכי שיט מוסמכים עם שנים של ניסיון בתחרויות באגם גארדה.', 'events_page'),

('events.overview.authentic_racing', 'es', 'Regatas Auténticas', 'events_page'),
('events.overview.authentic_racing', 'pl', 'Autentyczne Wyścigi', 'events_page'),
('events.overview.authentic_racing', 'he', 'תחרות אותנטית', 'events_page'),

('events.overview.authentic_racing_desc', 'es', 'Participa en regatas reales de yates con cronometraje oficial, puntuación y ceremonias de medallas.', 'events_page'),
('events.overview.authentic_racing_desc', 'it', 'Partecipa a vere regate di yacht con cronometraggio ufficiale, punteggio e cerimonie di premiazione.', 'events_page'),
('events.overview.authentic_racing_desc', 'pl', 'Weź udział w prawdziwych regatach jachtowych z oficjalnym pomiarem czasu, punktacją i ceremoniami medalowymi.', 'events_page'),
('events.overview.authentic_racing_desc', 'he', 'השתתף במירוצי יאכטות אמיתיים עם תזמון רשמי, ניקוד וטקסי מדליות.', 'events_page'),

('events.overview.professional_documentation', 'es', 'Documentación Profesional', 'events_page'),
('events.overview.professional_documentation', 'pl', 'Profesjonalna Dokumentacja', 'events_page'),
('events.overview.professional_documentation', 'he', 'תיעוד מקצועי', 'events_page'),

('events.overview.professional_documentation_desc', 'es', 'Fotos y videos de alta calidad de tu experiencia, entregados en 24 horas.', 'events_page'),
('events.overview.professional_documentation_desc', 'it', 'Foto e video di alta qualità della tua esperienza, consegnati entro 24 ore.', 'events_page'),
('events.overview.professional_documentation_desc', 'pl', 'Wysokiej jakości zdjęcia i filmy z Twojego doświadczenia, dostarczane w ciągu 24 godzin.', 'events_page'),
('events.overview.professional_documentation_desc', 'he', 'תמונות וסרטונים באיכות גבוהה של החוויה שלך, מסופקים תוך 24 שעות.', 'events_page'),

('events.overview.racing_format', 'es', 'Formato de Competición', 'events_page'),
('events.overview.racing_format', 'pl', 'Format Wyścigu', 'events_page'),
('events.overview.racing_format', 'he', 'פורמט התחרות', 'events_page'),

('events.overview.pro_level_regatta', 'es', 'Regata de Nivel Profesional de Un Día', 'events_page'),
('events.overview.pro_level_regatta', 'it', 'Regata di Livello Professionale di Un Giorno', 'events_page'),
('events.overview.pro_level_regatta', 'pl', 'Profesjonalne Jednodniowe Regaty', 'events_page'),
('events.overview.pro_level_regatta', 'he', 'רגטה מקצועית ליום אחד', 'events_page'),

-- J/70 yachts translations
('events.overview.j70_yachts', 'es', 'Regatas realizadas en yates de vela profesionales de clase J/70', 'events_page'),
('events.overview.j70_yachts', 'it', 'Regate tenute su yacht a vela professionali di classe J/70', 'events_page'),
('events.overview.j70_yachts', 'fr', 'Courses tenues sur des yachts à voile professionnels de classe J/70', 'events_page'),
('events.overview.j70_yachts', 'pl', 'Wyścigi odbywają się na profesjonalnych jachtach żaglowych klasy J/70', 'events_page'),
('events.overview.j70_yachts', 'he', 'תחרויות נערכות על יאכטות מפרש מקצועיות מסוג J/70', 'events_page'),

-- Licensed skipper translations
('events.overview.licensed_skipper', 'es', 'Cada barco incluye un patrón con licencia y una tripulación completa', 'events_page'),
('events.overview.licensed_skipper', 'it', 'Ogni barca include uno skipper con licenza e un equipaggio completo', 'events_page'),
('events.overview.licensed_skipper', 'fr', 'Chaque bateau comprend un skipper licencié et un équipage complet', 'events_page'),
('events.overview.licensed_skipper', 'pl', 'Każda łódź zawiera licencjonowanego skippera i pełną załogę', 'events_page'),
('events.overview.licensed_skipper', 'he', 'כל סירה כוללת סקיפר מורשה וצוות מלא', 'events_page'),

-- Official races translations
('events.overview.official_races', 'es', '3-5 regatas oficiales por día, puntuadas según las reglas del deporte de vela', 'events_page'),
('events.overview.official_races', 'it', '3-5 regate ufficiali al giorno, punteggiate secondo le regole dello sport velico', 'events_page'),
('events.overview.official_races', 'fr', '3 à 5 courses officielles par jour, notées selon les règles du sport de la voile', 'events_page'),
('events.overview.official_races', 'pl', '3-5 oficjalnych wyścigów dziennie, punktowanych zgodnie z zasadami sportu żeglarskiego', 'events_page'),
('events.overview.official_races', 'he', '3-5 מירוצים רשמיים ביום, עם ניקוד לפי חוקי ספורט השיט', 'events_page'),

-- Judging team translations
('events.overview.judging_team', 'es', 'Supervisado por un equipo de jueces calificados y barcos de apoyo técnico', 'events_page'),
('events.overview.judging_team', 'it', 'Supervisionato da un team di giudici qualificati e barche di supporto tecnico', 'events_page'),
('events.overview.judging_team', 'fr', 'Supervisé par une équipe de juges qualifiés et des bateaux de support technique', 'events_page'),
('events.overview.judging_team', 'pl', 'Nadzorowane przez wykwalifikowany zespół sędziowski i łodzie wsparcia technicznego', 'events_page'),
('events.overview.judging_team', 'he', 'בפיקוח צוות שופטים מוסמך וסירות תמיכה טכנית', 'events_page'),

-- Medal ceremony translations
('events.overview.medal_ceremony_certificates', 'es', 'Ceremonia de medallas y certificados para las mejores tripulaciones', 'events_page'),
('events.overview.medal_ceremony_certificates', 'it', 'Cerimonia delle medaglie e certificati per i migliori equipaggi', 'events_page'),
('events.overview.medal_ceremony_certificates', 'fr', 'Cérémonie de remise des médailles et certificats pour les meilleurs équipages', 'events_page'),
('events.overview.medal_ceremony_certificates', 'pl', 'Ceremonia medalowa i certyfikaty dla najlepszych załóg', 'events_page'),
('events.overview.medal_ceremony_certificates', 'he', 'טקס מדליות ותעודות לצוותים המובילים', 'events_page'),

-- Schedule section translations
('events.schedule.daily_schedule', 'es', 'Programa Diario', 'events_page'),
('events.schedule.daily_schedule', 'it', 'Programma Giornaliero', 'events_page'),
('events.schedule.daily_schedule', 'fr', 'Programme Quotidien', 'events_page'),
('events.schedule.daily_schedule', 'de', 'Tagesplan', 'events_page'),
('events.schedule.daily_schedule', 'pl', 'Harmonogram Dzienny', 'events_page'),
('events.schedule.daily_schedule', 'he', 'לוח זמנים יומי', 'events_page'),

('events.schedule.morning_session', 'es', 'Sesión Matutina', 'events_page'),
('events.schedule.morning_session', 'it', 'Sessione Mattutina', 'events_page'),
('events.schedule.morning_session', 'fr', 'Session du Matin', 'events_page'),
('events.schedule.morning_session', 'de', 'Vormittagssitzung', 'events_page'),
('events.schedule.morning_session', 'pl', 'Sesja Poranna', 'events_page'),
('events.schedule.morning_session', 'he', 'מפגש בוקר', 'events_page'),

('events.schedule.afternoon_session', 'es', 'Sesión Vespertina', 'events_page'),
('events.schedule.afternoon_session', 'it', 'Sessione Pomeridiana', 'events_page'),
('events.schedule.afternoon_session', 'fr', 'Session de l''Après-midi', 'events_page'),
('events.schedule.afternoon_session', 'de', 'Nachmittagssitzung', 'events_page'),
('events.schedule.afternoon_session', 'pl', 'Sesja Popołudniowa', 'events_page'),
('events.schedule.afternoon_session', 'he', 'מפגש אחר הצהריים', 'events_page'),

-- Schedule activities translations
('events.schedule.welcome_registration', 'es', 'Bienvenida y Registro', 'events_page'),
('events.schedule.welcome_registration', 'it', 'Benvenuto e Registrazione', 'events_page'),
('events.schedule.welcome_registration', 'fr', 'Accueil et Inscription', 'events_page'),
('events.schedule.welcome_registration', 'de', 'Willkommen & Registrierung', 'events_page'),
('events.schedule.welcome_registration', 'pl', 'Powitanie i Rejestracja', 'events_page'),
('events.schedule.welcome_registration', 'he', 'קבלת פנים ורישום', 'events_page'),

('events.schedule.welcome_registration_desc', 'es', 'Conoce a tu patrón y compañeros navegantes', 'events_page'),
('events.schedule.welcome_registration_desc', 'it', 'Incontra il tuo skipper e i compagni di navigazione', 'events_page'),
('events.schedule.welcome_registration_desc', 'fr', 'Rencontrez votre skipper et vos compagnons de navigation', 'events_page'),
('events.schedule.welcome_registration_desc', 'de', 'Treffen Sie Ihren Skipper und Mitsegler', 'events_page'),
('events.schedule.welcome_registration_desc', 'pl', 'Poznaj swojego skippera i towarzyszy żeglarzy', 'events_page'),
('events.schedule.welcome_registration_desc', 'ru', 'Познакомьтесь со шкипером и товарищами по плаванию', 'events_page'),
('events.schedule.welcome_registration_desc', 'he', 'פגוש את הסקיפר שלך ואת חבריך למפרשים', 'events_page'),

('events.schedule.safety_briefing', 'es', 'Instrucciones de Seguridad', 'events_page'),
('events.schedule.safety_briefing', 'it', 'Briefing di Sicurezza', 'events_page'),
('events.schedule.safety_briefing', 'fr', 'Briefing de Sécurité', 'events_page'),
('events.schedule.safety_briefing', 'de', 'Sicherheitseinweisung', 'events_page'),
('events.schedule.safety_briefing', 'pl', 'Instruktaż Bezpieczeństwa', 'events_page'),
('events.schedule.safety_briefing', 'ru', 'Инструктаж по безопасности', 'events_page'),
('events.schedule.safety_briefing', 'he', 'תדרוך בטיחות', 'events_page'),

('events.schedule.safety_briefing_desc', 'es', 'Procedimientos esenciales de seguridad y visión general del equipo', 'events_page'),
('events.schedule.safety_briefing_desc', 'it', 'Procedure essenziali di sicurezza e panoramica dell''attrezzatura', 'events_page'),
('events.schedule.safety_briefing_desc', 'fr', 'Procédures de sécurité essentielles et aperçu de l''équipement', 'events_page'),
('events.schedule.safety_briefing_desc', 'de', 'Wesentliche Sicherheitsverfahren und Ausrüstungsübersicht', 'events_page'),
('events.schedule.safety_briefing_desc', 'pl', 'Podstawowe procedury bezpieczeństwa i przegląd sprzętu', 'events_page'),
('events.schedule.safety_briefing_desc', 'ru', 'Основные процедуры безопасности и обзор оборудования', 'events_page'),
('events.schedule.safety_briefing_desc', 'he', 'נהלי בטיחות חיוניים וסקירת ציוד', 'events_page'),

('events.schedule.sailing_basics', 'es', 'Conceptos Básicos de Navegación', 'events_page'),
('events.schedule.sailing_basics', 'it', 'Basi della Vela', 'events_page'),
('events.schedule.sailing_basics', 'fr', 'Bases de la Voile', 'events_page'),
('events.schedule.sailing_basics', 'de', 'Grundlagen des Segelns', 'events_page'),
('events.schedule.sailing_basics', 'pl', 'Podstawy Żeglowania', 'events_page'),
('events.schedule.sailing_basics', 'ru', 'Основы парусного спорта', 'events_page'),
('events.schedule.sailing_basics', 'he', 'יסודות השיט', 'events_page'),

('events.schedule.sailing_basics_desc', 'es', 'Aprende técnicas fundamentales de navegación', 'events_page'),
('events.schedule.sailing_basics_desc', 'it', 'Impara le tecniche fondamentali della vela', 'events_page'),
('events.schedule.sailing_basics_desc', 'fr', 'Apprenez les techniques fondamentales de la voile', 'events_page'),
('events.schedule.sailing_basics_desc', 'de', 'Lernen Sie grundlegende Segeltechniken', 'events_page'),
('events.schedule.sailing_basics_desc', 'pl', 'Naucz się podstawowych technik żeglarskich', 'events_page'),
('events.schedule.sailing_basics_desc', 'ru', 'Изучите фундаментальные техники парусного спорта', 'events_page'),
('events.schedule.sailing_basics_desc', 'he', 'למד טכניקות שיט בסיסיות', 'events_page'),

('events.schedule.first_race', 'es', 'Primera Regata', 'events_page'),
('events.schedule.first_race', 'it', 'Prima Regata', 'events_page'),
('events.schedule.first_race', 'fr', 'Première Course', 'events_page'),
('events.schedule.first_race', 'de', 'Erstes Rennen', 'events_page'),
('events.schedule.first_race', 'pl', 'Pierwszy Wyścig', 'events_page'),
('events.schedule.first_race', 'ru', 'Первая гонка', 'events_page'),
('events.schedule.first_race', 'he', 'מירוץ ראשון', 'events_page'),

('events.schedule.first_race_desc', 'es', 'Regata de práctica para sentirse cómodo', 'events_page'),
('events.schedule.first_race_desc', 'it', 'Regata di pratica per prendere confidenza', 'events_page'),
('events.schedule.first_race_desc', 'fr', 'Course d''entraînement pour se sentir à l''aise', 'events_page'),
('events.schedule.first_race_desc', 'de', 'Übungsrennen zum Eingewöhnen', 'events_page'),
('events.schedule.first_race_desc', 'pl', 'Wyścig treningowy, aby poczuć się komfortowo', 'events_page'),
('events.schedule.first_race_desc', 'ru', 'Тренировочная гонка для освоения', 'events_page'),
('events.schedule.first_race_desc', 'he', 'מירוץ אימון כדי להרגיש בנוח', 'events_page'),

('events.schedule.medal_ceremony_award', 'es', 'Ceremonia de Medallas', 'events_page'),
('events.schedule.medal_ceremony_award', 'it', 'Cerimonia delle Medaglie', 'events_page'),
('events.schedule.medal_ceremony_award', 'fr', 'Cérémonie des Médailles', 'events_page'),
('events.schedule.medal_ceremony_award', 'de', 'Medaillenzeremonie', 'events_page'),
('events.schedule.medal_ceremony_award', 'pl', 'Ceremonia Medalowa', 'events_page'),
('events.schedule.medal_ceremony_award', 'ru', 'Церемония награждения', 'events_page'),
('events.schedule.medal_ceremony_award', 'he', 'טקס מדליות', 'events_page'),

('events.schedule.medal_ceremony_desc', 'es', 'Entrega de premios y certificados', 'events_page'),
('events.schedule.medal_ceremony_desc', 'it', 'Premiazioni e consegna dei certificati', 'events_page'),
('events.schedule.medal_ceremony_desc', 'fr', 'Remise des prix et des certificats', 'events_page'),
('events.schedule.medal_ceremony_desc', 'de', 'Preisverleihung und Zertifikatsübergabe', 'events_page'),
('events.schedule.medal_ceremony_desc', 'pl', 'Wręczenie nagród i certyfikatów', 'events_page'),
('events.schedule.medal_ceremony_desc', 'ru', 'Вручение наград и сертификатов', 'events_page'),
('events.schedule.medal_ceremony_desc', 'he', 'הענקת פרסים ותעודות', 'events_page'),

('events.schedule.photo_session', 'es', 'Sesión Fotográfica', 'events_page'),
('events.schedule.photo_session', 'it', 'Sessione Fotografica', 'events_page'),
('events.schedule.photo_session', 'fr', 'Séance Photo', 'events_page'),
('events.schedule.photo_session', 'de', 'Fotosession', 'events_page'),
('events.schedule.photo_session', 'pl', 'Sesja Zdjęciowa', 'events_page'),
('events.schedule.photo_session', 'ru', 'Фотосессия', 'events_page'),
('events.schedule.photo_session', 'he', 'מפגש צילום', 'events_page'),

('events.schedule.photo_session_desc', 'es', 'Fotos profesionales con tus medallas', 'events_page'),
('events.schedule.photo_session_desc', 'it', 'Foto professionali con le tue medaglie', 'events_page'),
('events.schedule.photo_session_desc', 'fr', 'Photos professionnelles avec vos médailles', 'events_page'),
('events.schedule.photo_session_desc', 'de', 'Professionelle Fotos mit Ihren Medaillen', 'events_page'),
('events.schedule.photo_session_desc', 'pl', 'Profesjonalne zdjęcia z Twoimi medalami', 'events_page'),
('events.schedule.photo_session_desc', 'ru', 'Профессиональные фотографии с вашими медалями', 'events_page'),
('events.schedule.photo_session_desc', 'he', 'צילומים מקצועיים עם המדליות שלך', 'events_page'),

-- Gallery section
('events.gallery.experience_gallery', 'es', 'Galería de Experiencias', 'events_page'),
('events.gallery.experience_gallery', 'it', 'Galleria dell''Esperienza', 'events_page'),
('events.gallery.experience_gallery', 'fr', 'Galerie d''Expériences', 'events_page'),
('events.gallery.experience_gallery', 'de', 'Erlebnisgalerie', 'events_page'),
('events.gallery.experience_gallery', 'pl', 'Galeria Doświadczeń', 'events_page'),
('events.gallery.experience_gallery', 'ru', 'Галерея впечатлений', 'events_page'),
('events.gallery.experience_gallery', 'he', 'גלריית חוויות', 'events_page'),

-- Weather section translations
('events.weather.typical_conditions', 'es', 'Condiciones Meteorológicas Típicas', 'events_page'),
('events.weather.typical_conditions', 'it', 'Condizioni Meteorologiche Tipiche', 'events_page'),
('events.weather.typical_conditions', 'fr', 'Conditions Météorologiques Typiques', 'events_page'),
('events.weather.typical_conditions', 'de', 'Typische Wetterbedingungen', 'events_page'),
('events.weather.typical_conditions', 'pl', 'Typowe Warunki Pogodowe', 'events_page'),
('events.weather.typical_conditions', 'ru', 'Типичные погодные условия', 'events_page'),
('events.weather.typical_conditions', 'he', 'תנאי מזג אוויר אופייניים', 'events_page'),

('events.weather.wind_speed', 'es', 'Velocidad del Viento', 'events_page'),
('events.weather.wind_speed', 'it', 'Velocità del Vento', 'events_page'),
('events.weather.wind_speed', 'fr', 'Vitesse du Vent', 'events_page'),
('events.weather.wind_speed', 'de', 'Windgeschwindigkeit', 'events_page'),
('events.weather.wind_speed', 'pl', 'Prędkość Wiatru', 'events_page'),
('events.weather.wind_speed', 'ru', 'Скорость ветра', 'events_page'),
('events.weather.wind_speed', 'he', 'מהירות רוח', 'events_page'),

('events.weather.wind_speed_value', 'es', '8-15 nudos', 'events_page'),
('events.weather.wind_speed_value', 'it', '8-15 nodi', 'events_page'),
('events.weather.wind_speed_value', 'fr', '8-15 nœuds', 'events_page'),
('events.weather.wind_speed_value', 'de', '8-15 Knoten', 'events_page'),
('events.weather.wind_speed_value', 'pl', '8-15 węzłów', 'events_page'),
('events.weather.wind_speed_value', 'ru', '8-15 узлов', 'events_page'),
('events.weather.wind_speed_value', 'he', '8-15 קשרים', 'events_page'),

('events.weather.temperature', 'es', 'Temperatura', 'events_page'),
('events.weather.temperature', 'it', 'Temperatura', 'events_page'),
('events.weather.temperature', 'fr', 'Température', 'events_page'),
('events.weather.temperature', 'de', 'Temperatur', 'events_page'),
('events.weather.temperature', 'pl', 'Temperatura', 'events_page'),
('events.weather.temperature', 'ru', 'Температура', 'events_page'),
('events.weather.temperature', 'he', 'טמפרטורה', 'events_page'),

('events.weather.temperature_value', 'es', '18-28°C', 'events_page'),
('events.weather.temperature_value', 'it', '18-28°C', 'events_page'),
('events.weather.temperature_value', 'fr', '18-28°C', 'events_page'),
('events.weather.temperature_value', 'de', '18-28°C', 'events_page'),
('events.weather.temperature_value', 'pl', '18-28°C', 'events_page'),
('events.weather.temperature_value', 'ru', '18-28°C', 'events_page'),
('events.weather.temperature_value', 'he', '18-28°C', 'events_page'),

('events.weather.visibility', 'es', 'Visibilidad', 'events_page'),
('events.weather.visibility', 'it', 'Visibilità', 'events_page'),
('events.weather.visibility', 'fr', 'Visibilité', 'events_page'),
('events.weather.visibility', 'de', 'Sicht', 'events_page'),
('events.weather.visibility', 'pl', 'Widoczność', 'events_page'),
('events.weather.visibility', 'ru', 'Видимость', 'events_page'),
('events.weather.visibility', 'he', 'ראות', 'events_page'),

('events.weather.visibility_value', 'es', 'Excelente', 'events_page'),
('events.weather.visibility_value', 'it', 'Eccellente', 'events_page'),
('events.weather.visibility_value', 'fr', 'Excellente', 'events_page'),
('events.weather.visibility_value', 'de', 'Ausgezeichnet', 'events_page'),
('events.weather.visibility_value', 'pl', 'Doskonała', 'events_page'),
('events.weather.visibility_value', 'ru', 'Отличная', 'events_page'),
('events.weather.visibility_value', 'he', 'מצוינת', 'events_page'),

('events.weather.water_temp', 'es', 'Temperatura del Agua', 'events_page'),
('events.weather.water_temp', 'it', 'Temperatura dell''Acqua', 'events_page'),
('events.weather.water_temp', 'fr', 'Température de l''Eau', 'events_page'),
('events.weather.water_temp', 'de', 'Wassertemperatur', 'events_page'),
('events.weather.water_temp', 'pl', 'Temperatura Wody', 'events_page'),
('events.weather.water_temp', 'ru', 'Температура воды', 'events_page'),
('events.weather.water_temp', 'he', 'טמפרטורת המים', 'events_page'),

('events.weather.water_temp_value', 'es', '16-24°C', 'events_page'),
('events.weather.water_temp_value', 'it', '16-24°C', 'events_page'),
('events.weather.water_temp_value', 'fr', '16-24°C', 'events_page'),
('events.weather.water_temp_value', 'de', '16-24°C', 'events_page'),
('events.weather.water_temp_value', 'pl', '16-24°C', 'events_page'),
('events.weather.water_temp_value', 'ru', '16-24°C', 'events_page'),
('events.weather.water_temp_value', 'he', '16-24°C', 'events_page'),

-- Equipment section translations
('events.equipment.equipment_provided', 'es', 'Equipamiento Proporcionado', 'events_page'),
('events.equipment.equipment_provided', 'it', 'Attrezzatura Fornita', 'events_page'),
('events.equipment.equipment_provided', 'fr', 'Équipement Fourni', 'events_page'),
('events.equipment.equipment_provided', 'de', 'Ausrüstung wird gestellt', 'events_page'),
('events.equipment.equipment_provided', 'pl', 'Dostarczany Sprzęt', 'events_page'),
('events.equipment.equipment_provided', 'ru', 'Предоставляемое оборудование', 'events_page'),
('events.equipment.equipment_provided', 'he', 'ציוד מסופק', 'events_page'),

('events.equipment.safety_first', 'es', 'La Seguridad Primero', 'events_page'),
('events.equipment.safety_first', 'it', 'La Sicurezza Prima di Tutto', 'events_page'),
('events.equipment.safety_first', 'fr', 'La Sécurité d''Abord', 'events_page'),
('events.equipment.safety_first', 'de', 'Sicherheit geht vor', 'events_page'),
('events.equipment.safety_first', 'pl', 'Bezpieczeństwo Przede Wszystkim', 'events_page'),
('events.equipment.safety_first', 'ru', 'Безопасность превыше всего', 'events_page'),
('events.equipment.safety_first', 'he', 'בטיחות תחילה', 'events_page'),

('events.equipment.safety_description', 'es', 'Todo el equipo de seguridad cumple con estándares internacionales. Nuestros barcos son inspeccionados y mantenidos regularmente según los más altos estándares. Cada participante recibe una instrucción completa de seguridad antes de la salida.', 'events_page'),
('events.equipment.safety_description', 'it', 'Tutta l''attrezzatura di sicurezza soddisfa gli standard internazionali. Le nostre barche sono regolarmente ispezionate e mantenute secondo i più alti standard. Ogni partecipante riceve un briefing completo sulla sicurezza prima della partenza.', 'events_page'),
('events.equipment.safety_description', 'fr', 'Tous les équipements de sécurité répondent aux normes internationales. Nos bateaux sont régulièrement inspectés et entretenus selon les normes les plus élevées. Chaque participant reçoit un briefing complet sur la sécurité avant le départ.', 'events_page'),
('events.equipment.safety_description', 'de', 'Alle Sicherheitsausrüstungen entsprechen internationalen Standards. Unsere Boote werden regelmäßig inspiziert und nach höchsten Standards gewartet. Jeder Teilnehmer erhält vor der Abfahrt eine umfassende Sicherheitseinweisung.', 'events_page'),
('events.equipment.safety_description', 'pl', 'Cały sprzęt bezpieczeństwa spełnia międzynarodowe standardy. Nasze łodzie są regularnie kontrolowane i utrzymywane zgodnie z najwyższymi standardami. Każdy uczestnik otrzymuje kompleksowe szkolenie bezpieczeństwa przed wyjściem w morze.', 'events_page'),
('events.equipment.safety_description', 'ru', 'Все оборудование безопасности соответствует международным стандартам. Наши лодки регулярно проверяются и обслуживаются по самым высоким стандартам. Каждый участник получает всесторонний инструктаж по безопасности перед отправлением.', 'events_page'),
('events.equipment.safety_description', 'he', 'כל ציוד הבטיחות עומד בתקנים בינלאומיים. הסירות שלנו נבדקות ומתוחזקות באופן קבוע לפי הסטנדרטים הגבוהים ביותר. כל משתתף מקבל תדרוך בטיחות מקיף לפני היציאה.', 'events_page'),

('events.equipment.premium_yachts', 'es', 'Yates Premium', 'events_page'),
('events.equipment.premium_yachts', 'it', 'Yacht Premium', 'events_page'),
('events.equipment.premium_yachts', 'fr', 'Yachts Premium', 'events_page'),
('events.equipment.premium_yachts', 'de', 'Premium-Yachten', 'events_page'),
('events.equipment.premium_yachts', 'pl', 'Jachty Premium', 'events_page'),
('events.equipment.premium_yachts', 'ru', 'Премиум-яхты', 'events_page'),
('events.equipment.premium_yachts', 'he', 'יאכטות פרימיום', 'events_page'),

('events.equipment.premium_yachts_desc', 'es', 'Utilizamos yates modernos de alto rendimiento J-70/J-80. Estos barcos son elegidos específicamente por sus capacidades de regata, manteniendo al mismo tiempo la comodidad y seguridad para nuestros participantes.', 'events_page'),
('events.equipment.premium_yachts_desc', 'it', 'Utilizziamo moderni yacht ad alte prestazioni J-70/J-80. Queste barche sono scelte specificatamente per le loro capacità di regata, mantenendo allo stesso tempo comfort e sicurezza per i nostri partecipanti.', 'events_page'),
('events.equipment.premium_yachts_desc', 'fr', 'Nous utilisons des yachts modernes J-70/J-80 à hautes performances. Ces bateaux sont spécifiquement choisis pour leurs capacités de course, tout en maintenant le confort et la sécurité pour nos participants.', 'events_page'),
('events.equipment.premium_yachts_desc', 'de', 'Wir verwenden moderne J-70/J-80 Hochleistungsyachten. Diese Boote werden speziell wegen ihrer Rennfähigkeiten ausgewählt, während Komfort und Sicherheit für unsere Teilnehmer gewährleistet sind.', 'events_page'),
('events.equipment.premium_yachts_desc', 'pl', 'Używamy nowoczesnych, wysokowydajnych jachtów J-70/J-80. Te łodzie są specjalnie wybrane ze względu na ich możliwości regatowe, przy jednoczesnym zachowaniu komfortu i bezpieczeństwa dla naszych uczestników.', 'events_page'),
('events.equipment.premium_yachts_desc', 'ru', 'Мы используем современные высокопроизводительные яхты J-70/J-80. Эти лодки выбраны специально за их гоночные возможности при сохранении комфорта и безопасности для наших участников.', 'events_page'),
('events.equipment.premium_yachts_desc', 'he', 'אנו משתמשים ביאכטות מודרניות בעלות ביצועים גבוהים מדגמי J-70/J-80. סירות אלו נבחרו במיוחד בשל יכולות המירוץ שלהן, תוך שמירה על נוחות ובטיחות למשתתפים שלנו.', 'events_page'),

('events.equipment.professional_j70_yacht', 'es', 'Yate de Regata Profesional J-70/J-80', 'events_page'),
('events.equipment.professional_j70_yacht', 'it', 'Yacht da Regata Professionale J-70/J-80', 'events_page'),
('events.equipment.professional_j70_yacht', 'fr', 'Yacht de Régate Professionnel J-70/J-80', 'events_page'),
('events.equipment.professional_j70_yacht', 'de', 'Professionelle J-70/J-80 Rennyacht', 'events_page'),
('events.equipment.professional_j70_yacht', 'pl', 'Profesjonalny Jacht Regatowy J-70/J-80', 'events_page'),
('events.equipment.professional_j70_yacht', 'ru', 'Профессиональная гоночная яхта J-70/J-80', 'events_page'),
('events.equipment.professional_j70_yacht', 'he', 'יאכטת מירוץ מקצועית J-70/J-80', 'events_page'),

('events.equipment.complete_list', 'es', 'Lista Completa de Equipamiento', 'events_page'),
('events.equipment.complete_list', 'it', 'Elenco Completo dell''Attrezzatura', 'events_page'),
('events.equipment.complete_list', 'fr', 'Liste Complète d''Équipement', 'events_page'),
('events.equipment.complete_list', 'de', 'Vollständige Ausrüstungsliste', 'events_page'),
('events.equipment.complete_list', 'pl', 'Kompletna Lista Sprzętu', 'events_page'),
('events.equipment.complete_list', 'ru', 'Полный список оборудования', 'events_page'),
('events.equipment.complete_list', 'he', 'רשימת ציוד מלאה', 'events_page'),

-- Equipment items translations
('events.equipment.racing_yacht', 'es', 'Yate de regata profesional (J-70/J-80)', 'events_page'),
('events.equipment.racing_yacht', 'it', 'Yacht da regata professionale (J-70/J-80)', 'events_page'),
('events.equipment.racing_yacht', 'fr', 'Yacht de course professionnel (J-70/J-80)', 'events_page'),
('events.equipment.racing_yacht', 'de', 'Professionelle Rennyacht (J-70/J-80)', 'events_page'),
('events.equipment.racing_yacht', 'pl', 'Profesjonalny jacht regatowy (J-70/J-80)', 'events_page'),
('events.equipment.racing_yacht', 'ru', 'Профессиональная гоночная яхта (J-70/J-80)', 'events_page'),
('events.equipment.racing_yacht', 'he', 'יאכטת מירוץ מקצועית (J-70/J-80)', 'events_page'),

('events.equipment.safety_equipment', 'es', 'Todo el equipo de seguridad (chalecos salvavidas, agua)', 'events_page'),
('events.equipment.safety_equipment', 'it', 'Tutta l''attrezzatura di sicurezza (giubbotti di salvataggio, acqua)', 'events_page'),
('events.equipment.safety_equipment', 'fr', 'Tout l''équipement de sécurité (gilets de sauvetage, eau)', 'events_page'),
('events.equipment.safety_equipment', 'de', 'Gesamte Sicherheitsausrüstung (Schwimmwesten, Wasser)', 'events_page'),
('events.equipment.safety_equipment', 'pl', 'Cały sprzęt bezpieczeństwa (kamizelki ratunkowe, woda)', 'events_page'),
('events.equipment.safety_equipment', 'ru', 'Все оборудование безопасности (спасательные жилеты, вода)', 'events_page'),
('events.equipment.safety_equipment', 'he', 'כל ציוד הבטיחות (חגורות הצלה, מים)', 'events_page'),

('events.equipment.sailing_gear', 'es', 'Equipo de navegación profesional', 'events_page'),
('events.equipment.sailing_gear', 'it', 'Attrezzatura professionale da vela', 'events_page'),
('events.equipment.sailing_gear', 'fr', 'Équipement de voile professionnel', 'events_page'),
('events.equipment.sailing_gear', 'de', 'Professionelle Segelausrüstung', 'events_page'),
('events.equipment.sailing_gear', 'pl', 'Profesjonalny sprzęt żeglarski', 'events_page'),
('events.equipment.sailing_gear', 'ru', 'Профессиональное парусное снаряжение', 'events_page'),
('events.equipment.sailing_gear', 'he', 'ציוד שיט מקצועי', 'events_page'),

('events.equipment.first_aid', 'es', 'Botiquín de primeros auxilios y equipo de emergencia', 'events_page'),
('events.equipment.first_aid', 'it', 'Kit di pronto soccorso e attrezzatura di emergenza', 'events_page'),
('events.equipment.first_aid', 'fr', 'Trousse de premiers secours et équipement d''urgence', 'events_page'),
('events.equipment.first_aid', 'de', 'Erste-Hilfe-Set und Notfallausrüstung', 'events_page'),
('events.equipment.first_aid', 'pl', 'Zestaw pierwszej pomocy i sprzęt awaryjny', 'events_page'),
('events.equipment.first_aid', 'ru', 'Аптечка первой помощи и аварийное оборудование', 'events_page'),
('events.equipment.first_aid', 'he', 'ערכת עזרה ראשונה וציוד חירום', 'events_page'),

('events.equipment.photo_equipment', 'es', 'Equipo fotográfico profesional', 'events_page'),
('events.equipment.photo_equipment', 'it', 'Attrezzatura fotografica professionale', 'events_page'),
('events.equipment.photo_equipment', 'fr', 'Équipement photographique professionnel', 'events_page'),
('events.equipment.photo_equipment', 'de', 'Professionelle Fotoausrüstung', 'events_page'),
('events.equipment.photo_equipment', 'pl', 'Profesjonalny sprzęt fotograficzny', 'events_page'),
('events.equipment.photo_equipment', 'ru', 'Профессиональное фотооборудование', 'events_page'),
('events.equipment.photo_equipment', 'he', 'ציוד צילום מקצועי', 'events_page'),

('events.equipment.medals_certificates', 'es', 'Medallas y certificados de regata', 'events_page'),
('events.equipment.medals_certificates', 'it', 'Medaglie e certificati di regata', 'events_page'),
('events.equipment.medals_certificates', 'fr', 'Médailles et certificats de régate', 'events_page'),
('events.equipment.medals_certificates', 'de', 'Rennmedaillen und Zertifikate', 'events_page'),
('events.equipment.medals_certificates', 'pl', 'Medale i certyfikaty regatowe', 'events_page'),
('events.equipment.medals_certificates', 'ru', 'Гоночные медали и сертификаты', 'events_page'),
('events.equipment.medals_certificates', 'he', 'מדליות ותעודות מירוץ', 'events_page'),

-- FAQ section translations
('events.faq.frequently_asked', 'es', 'Preguntas Frecuentes', 'events_page'),
('events.faq.frequently_asked', 'it', 'Domande Frequenti', 'events_page'),
('events.faq.frequently_asked', 'fr', 'Questions Fréquemment Posées', 'events_page'),
('events.faq.frequently_asked', 'de', 'Häufig gestellte Fragen', 'events_page'),
('events.faq.frequently_asked', 'pl', 'Często Zadawane Pytania', 'events_page'),
('events.faq.frequently_asked', 'ru', 'Часто задаваемые вопросы', 'events_page'),
('events.faq.frequently_asked', 'he', 'שאלות נפוצות', 'events_page'),

('events.faq.sailing_experience', 'es', '¿Necesito experiencia en navegación?', 'events_page'),
('events.faq.sailing_experience', 'it', 'Ho bisogno di esperienza di vela?', 'events_page'),
('events.faq.sailing_experience', 'fr', 'Ai-je besoin d''une expérience en voile?', 'events_page'),
('events.faq.sailing_experience', 'de', 'Benötige ich Segelerfahrung?', 'events_page'),
('events.faq.sailing_experience', 'pl', 'Czy potrzebuję doświadczenia żeglarskiego?', 'events_page'),
('events.faq.sailing_experience', 'ru', 'Нужен ли мне опыт в парусном спорте?', 'events_page'),
('events.faq.sailing_experience', 'he', 'האם אני צריך ניסיון בשיט?', 'events_page'),

('events.faq.sailing_experience_answer', 'es', '¡No se requiere experiencia en navegación! Nuestros patrones profesionales te enseñarán todo lo que necesitas saber. Damos la bienvenida tanto a principiantes completos como a navegantes experimentados.', 'events_page'),
('events.faq.sailing_experience_answer', 'it', 'Non è richiesta alcuna esperienza di vela! I nostri skipper professionisti ti insegneranno tutto ciò che devi sapere. Diamo il benvenuto sia ai principianti assoluti che ai velisti esperti.', 'events_page'),
('events.faq.sailing_experience_answer', 'fr', 'Aucune expérience de voile n''est requise! Nos skippers professionnels vous apprendront tout ce que vous devez savoir. Nous accueillons aussi bien les débutants complets que les marins expérimentés.', 'events_page'),
('events.faq.sailing_experience_answer', 'de', 'Es ist keine Segelerfahrung erforderlich! Unsere professionellen Skipper bringen Ihnen alles bei, was Sie wissen müssen. Wir heißen sowohl absolute Anfänger als auch erfahrene Segler willkommen.', 'events_page'),
('events.faq.sailing_experience_answer', 'pl', 'Doświadczenie żeglarskie nie jest wymagane! Nasi profesjonalni skipperzy nauczą Cię wszystkiego, co musisz wiedzieć. Witamy zarówno całkowitych początkujących, jak i doświadczonych żeglarzy.', 'events_page'),
('events.faq.sailing_experience_answer', 'ru', 'Опыт в парусном спорте не требуется! Наши профессиональные шкиперы научат вас всему, что вам нужно знать. Мы приветствуем как абсолютных новичков, так и опытных моряков.', 'events_page'),
('events.faq.sailing_experience_answer', 'he', 'לא נדרש ניסיון בשיט! הסקיפרים המקצועיים שלנו ילמדו אותך כל מה שאתה צריך לדעת. אנחנו מקבלים בברכה הן מתחילים מוחלטים והן ימאים מנוסים.', 'events_page'),

('events.faq.what_to_bring', 'es', '¿Qué debo traer?', 'events_page'),
('events.faq.what_to_bring', 'it', 'Cosa dovrei portare?', 'events_page'),
('events.faq.what_to_bring', 'fr', 'Que dois-je apporter?', 'events_page'),
('events.faq.what_to_bring', 'de', 'Was soll ich mitbringen?', 'events_page'),
('events.faq.what_to_bring', 'pl', 'Co powinienem przynieść?', 'events_page'),
('events.faq.what_to_bring', 'ru', 'Что мне нужно взять с собой?', 'events_page'),
('events.faq.what_to_bring', 'he', 'מה עלי להביא?', 'events_page'),

('events.faq.what_to_bring_answer', 'es', 'Trae ropa cómoda, protector solar, un sombrero y ropa de cambio. Proporcionamos todo el equipo de navegación y de seguridad.', 'events_page'),
('events.faq.what_to_bring_answer', 'it', 'Porta abiti comodi, crema solare, un cappello e un cambio di vestiti. Noi forniamo tutta l''attrezzatura da vela e di sicurezza.', 'events_page'),
('events.faq.what_to_bring_answer', 'fr', 'Apportez des vêtements confortables, de la crème solaire, un chapeau et des vêtements de rechange. Nous fournissons tout l''équipement de voile et de sécurité.', 'events_page'),
('events.faq.what_to_bring_answer', 'de', 'Bringen Sie bequeme Kleidung, Sonnencreme, einen Hut und Wechselkleidung mit. Wir stellen die gesamte Segel- und Sicherheitsausrüstung zur Verfügung.', 'events_page'),
('events.faq.what_to_bring_answer', 'pl', 'Przynieś wygodne ubrania, krem przeciwsłoneczny, kapelusz i ubrania na zmianę. Zapewniamy cały sprzęt żeglarski i bezpieczeństwa.', 'events_page'),
('events.faq.what_to_bring_answer', 'ru', 'Возьмите с собой удобную одежду, солнцезащитный крем, шляпу и сменную одежду. Мы предоставляем все парусное оборудование и снаряжение для безопасности.', 'events_page'),
('events.faq.what_to_bring_answer', 'he', 'הבא בגדים נוחים, קרם הגנה, כובע ובגדים להחלפה. אנחנו מספקים את כל ציוד השיט והבטיחות.', 'events_page'),

('events.faq.bad_weather', 'es', '¿Qué pasa si el clima es malo?', 'events_page'),
('events.faq.bad_weather', 'it', 'Cosa succede se il tempo è brutto?', 'events_page'),
('events.faq.bad_weather', 'fr', 'Que se passe-t-il si le temps est mauvais?', 'events_page'),
('events.faq.bad_weather', 'de', 'Was ist, wenn das Wetter schlecht ist?', 'events_page'),
('events.faq.bad_weather', 'pl', 'Co jeśli pogoda jest zła?', 'events_page'),
('events.faq.bad_weather', 'ru', 'Что, если погода плохая?', 'events_page'),
('events.faq.bad_weather', 'he', 'מה קורה אם מזג האוויר גרוע?', 'events_page'),

('events.faq.bad_weather_answer', 'es', 'La seguridad es nuestra prioridad. Si las condiciones no son seguras, reprogramaremos tu experiencia sin costo adicional. La lluvia ligera no nos detiene, ¡es parte de la aventura!', 'events_page'),
('events.faq.bad_weather_answer', 'it', 'La sicurezza è la nostra priorità. Se le condizioni non sono sicure, riprogrammeremo la tua esperienza senza costi aggiuntivi. La pioggia leggera non ci ferma, fa parte dell''avventura!', 'events_page'),
('events.faq.bad_weather_answer', 'fr', 'La sécurité est notre priorité. Si les conditions ne sont pas sûres, nous reprogrammerons votre expérience sans frais supplémentaires. La pluie légère ne nous arrête pas - c''est une partie de l''aventure!', 'events_page'),
('events.faq.bad_weather_answer', 'de', 'Sicherheit ist unsere Priorität. Bei unsicheren Bedingungen verschieben wir Ihr Erlebnis ohne zusätzliche Kosten. Leichter Regen hält uns nicht auf - das gehört zum Abenteuer dazu!', 'events_page'),
('events.faq.bad_weather_answer', 'pl', 'Bezpieczeństwo jest naszym priorytetem. Jeśli warunki są niebezpieczne, przeniesiemy Twoje doświadczenie bez dodatkowych kosztów. Lekki deszcz nas nie powstrzyma - to część przygody!', 'events_page'),
('events.faq.bad_weather_answer', 'ru', 'Безопасность – наш приоритет. Если условия небезопасны, мы перенесем ваше мероприятие без дополнительной оплаты. Легкий дождь нас не останавливает – это часть приключения!', 'events_page'),
('events.faq.bad_weather_answer', 'he', 'בטיחות היא העדיפות שלנו. אם התנאים אינם בטוחים, נתזמן מחדש את החוויה שלך ללא עלות נוספת. גשם קל אינו עוצר אותנו - זה חלק מההרפתקה!', 'events_page'),

('events.faq.people_per_boat', 'es', '¿Cuántas personas por barco?', 'events_page'),
('events.faq.people_per_boat', 'it', 'Quante persone per barca?', 'events_page'),
('events.faq.people_per_boat', 'fr', 'Combien de personnes par bateau?', 'events_page'),
('events.faq.people_per_boat', 'de', 'Wie viele Personen pro Boot?', 'events_page'),
('events.faq.people_per_boat', 'pl', 'Ile osób na łódź?', 'events_page'),
('events.faq.people_per_boat', 'ru', 'Сколько человек на лодке?', 'events_page'),
('events.faq.people_per_boat', 'he', 'כמה אנשים לסירה?', 'events_page'),

('events.faq.people_per_boat_answer', 'es', 'Cada yate tiene capacidad para 4-5 participantes más el patrón profesional. Esto asegura una atención personalizada.', 'events_page'),
('events.faq.people_per_boat_answer', 'it', 'Ogni yacht ospita 4-5 partecipanti più lo skipper professionale. Questo garantisce un''attenzione personalizzata.', 'events_page'),
('events.faq.people_per_boat_answer', 'fr', 'Chaque yacht peut accueillir 4 à 5 participants plus le skipper professionnel. Cela assure une attention personnalisée.', 'events_page'),
('events.faq.people_per_boat_answer', 'de', 'Jede Yacht bietet Platz für 4-5 Teilnehmer plus den professionellen Skipper. Dies gewährleistet persönliche Aufmerksamkeit.', 'events_page'),
('events.faq.people_per_boat_answer', 'pl', 'Każdy jacht mieści 4-5 uczestników plus profesjonalnego skippera. Zapewnia to spersonalizowaną uwagę.', 'events_page'),
('events.faq.people_per_boat_answer', 'ru', 'Каждая яхта вмещает 4-5 участников плюс профессионального шкипера. Это обеспечивает индивидуальное внимание.', 'events_page'),
('events.faq.people_per_boat_answer', 'he', 'כל יאכטה מכילה 4-5 משתתפים בנוסף לסקיפר המקצועי. זה מבטיח תשומת לב אישית.', 'events_page'),

('events.faq.bring_camera', 'es', '¿Puedo traer mi cámara?', 'events_page'),
('events.faq.bring_camera', 'it', 'Posso portare la mia fotocamera?', 'events_page'),
('events.faq.bring_camera', 'fr', 'Puis-je apporter mon appareil photo?', 'events_page'),
('events.faq.bring_camera', 'de', 'Kann ich meine Kamera mitbringen?', 'events_page'),
('events.faq.bring_camera', 'pl', 'Czy mogę przynieść swój aparat?', 'events_page'),
('events.faq.bring_camera', 'ru', 'Могу ли я взять с собой фотоаппарат?', 'events_page'),
('events.faq.bring_camera', 'he', 'האם אני יכול להביא את המצלמה שלי?', 'events_page'),

('events.faq.bring_camera_answer', 'es', '¡Absolutamente! También ofrecemos servicios de fotografía profesional. Recibirás fotos y videos de alta calidad de tu experiencia de regata dentro de las 24 horas.', 'events_page'),
('events.faq.bring_camera_answer', 'it', 'Assolutamente! Offriamo anche servizi fotografici professionali. Riceverai foto e video di alta qualità della tua esperienza di regata entro 24 ore.', 'events_page'),
('events.faq.bring_camera_answer', 'fr', 'Absolument! Nous proposons également des services de photographie professionnelle. Vous recevrez des photos et vidéos de haute qualité de votre expérience de régate dans les 24 heures.', 'events_page'),
('events.faq.bring_camera_answer', 'de', 'Auf jeden Fall! Wir bieten auch professionelle Fotodienste an. Sie erhalten hochwertige Fotos und Videos Ihres Rennerlebnisses innerhalb von 24 Stunden.', 'events_page'),
('events.faq.bring_camera_answer', 'pl', 'Absolutnie! Oferujemy również profesjonalne usługi fotograficzne. Otrzymasz wysokiej jakości zdjęcia i filmy z Twojego doświadczenia regatowego w ciągu 24 godzin.', 'events_page'),
('events.faq.bring_camera_answer', 'ru', 'Абсолютно! Мы также предоставляем услуги профессиональной фотографии. Вы получите высококачественные фотографии и видео вашего гоночного опыта в течение 24 часов.', 'events_page'),
('events.faq.bring_camera_answer', 'he', 'בהחלט! אנו גם מציעים שירותי צילום מקצועיים. תקבל תמונות וסרטונים באיכות גבוהה מחוויית המירוץ שלך תוך 24 שעות.', 'events_page')

ON CONFLICT (key, language_code) DO NOTHING;