/*
  # Home Page Translations
  
  This migration adds translations for the home page content in multiple languages.
  
  1. Translations added:
     - Hero section (title, subtitle, CTA buttons)
     - Features section
     - Experience section
     - Testimonials section
     - Location section
     - CTA section
*/

-- Insert Home Page translations
INSERT INTO translations (key, language_code, text, category) VALUES
-- Hero Section
('home.hero.title', 'en', 'Experience the Thrill of Yacht Racing', 'home_page'),
('home.hero.title', 'de', 'Erleben Sie den Nervenkitzel des Yachtrennsports', 'home_page'),
('home.hero.title', 'fr', 'Vivez le frisson de la course de yachts', 'home_page'),
('home.hero.title', 'it', 'Vivi l''emozione delle regate veliche', 'home_page'),
('home.hero.title', 'es', 'Experimenta la emoción de las regatas de yates', 'home_page'),
('home.hero.title', 'pl', 'Przeżyj emocje wyścigów jachtowych', 'home_page'),
('home.hero.title', 'he', 'חווה את הריגוש של מירוצי יאכטות', 'home_page'),
('home.hero.title', 'ru', 'Почувствуйте азарт парусных гонок', 'home_page'),

('home.hero.subtitle', 'en', 'Daily yacht racing experiences in world-famous Lake Garda with professional skippers, racing medals, and unforgettable memories', 'home_page'),
('home.hero.subtitle', 'de', 'Tägliche Yachtrennen am weltberühmten Gardasee mit professionellen Skippern, Rennmedaillen und unvergesslichen Erinnerungen', 'home_page'),
('home.hero.subtitle', 'fr', 'Expériences quotidiennes de course de yachts sur le célèbre lac de Garde avec des skippers professionnels, des médailles de course et des souvenirs inoubliables', 'home_page'),
('home.hero.subtitle', 'it', 'Esperienze quotidiane di regata velica sul famoso Lago di Garda con skipper professionali, medaglie di regata e ricordi indimenticabili', 'home_page'),
('home.hero.subtitle', 'es', 'Experiencias diarias de regatas de yates en el mundialmente famoso Lago de Garda con patrones profesionales, medallas de regata y recuerdos inolvidables', 'home_page'),
('home.hero.subtitle', 'pl', 'Codzienne doświadczenia wyścigów jachtowych na słynnym jeziorze Garda z profesjonalnymi sternikami, medalami wyścigowymi i niezapomnianymi wspomnieniami', 'home_page'),
('home.hero.subtitle', 'he', 'חוויות יומיות של מירוצי יאכטות באגם גארדה המפורסם עם רבי חובלים מקצועיים, מדליות מירוץ וזכרונות בלתי נשכחים', 'home_page'),
('home.hero.subtitle', 'ru', 'Ежедневные парусные гонки на всемирно известном озере Гарда с профессиональными шкиперами, медалями и незабываемыми воспоминаниями', 'home_page'),

('home.hero.price', 'en', 'per person • Full day experience', 'home_page'),
('home.hero.price', 'de', 'pro Person • Ganztägiges Erlebnis', 'home_page'),
('home.hero.price', 'fr', 'par personne • Expérience d''une journée complète', 'home_page'),
('home.hero.price', 'it', 'per persona • Esperienza di un giorno intero', 'home_page'),
('home.hero.price', 'es', 'por persona • Experiencia de día completo', 'home_page'),
('home.hero.price', 'pl', 'za osobę • Całodniowe doświadczenie', 'home_page'),
('home.hero.price', 'he', 'לאדם • חוויה ליום שלם', 'home_page'),
('home.hero.price', 'ru', 'на человека • Полный день', 'home_page'),

('home.hero.cta', 'en', 'Book Your Adventure', 'home_page'),
('home.hero.cta', 'de', 'Buchen Sie Ihr Abenteuer', 'home_page'),
('home.hero.cta', 'fr', 'Réservez votre aventure', 'home_page'),
('home.hero.cta', 'it', 'Prenota la tua avventura', 'home_page'),
('home.hero.cta', 'es', 'Reserva tu aventura', 'home_page'),
('home.hero.cta', 'pl', 'Zarezerwuj swoją przygodę', 'home_page'),
('home.hero.cta', 'he', 'הזמן את ההרפתקה שלך', 'home_page'),
('home.hero.cta', 'ru', 'Забронировать приключение', 'home_page'),

-- Features Section
('home.features.title', 'en', 'Why Choose Garda Racing?', 'home_page'),
('home.features.title', 'de', 'Warum Garda Racing wählen?', 'home_page'),
('home.features.title', 'fr', 'Pourquoi choisir Garda Racing?', 'home_page'),
('home.features.title', 'it', 'Perché scegliere Garda Racing?', 'home_page'),
('home.features.title', 'es', '¿Por qué elegir Garda Racing?', 'home_page'),
('home.features.title', 'pl', 'Dlaczego warto wybrać Garda Racing?', 'home_page'),
('home.features.title', 'he', 'למה לבחור בגארדה רייסינג?', 'home_page'),
('home.features.title', 'ru', 'Почему стоит выбрать Garda Racing?', 'home_page'),

('home.features.subtitle', 'en', 'We provide the complete yacht racing experience with professional guidance, premium equipment, and memories that last a lifetime.', 'home_page'),
('home.features.subtitle', 'de', 'Wir bieten das komplette Yachtrennerlebnis mit professioneller Anleitung, erstklassiger Ausrüstung und Erinnerungen, die ein Leben lang halten.', 'home_page'),
('home.features.subtitle', 'fr', 'Nous offrons l''expérience complète de course de yacht avec des conseils professionnels, un équipement haut de gamme et des souvenirs qui durent toute une vie.', 'home_page'),
('home.features.subtitle', 'it', 'Offriamo l''esperienza completa di regata velica con guida professionale, attrezzature premium e ricordi che durano tutta la vita.', 'home_page'),
('home.features.subtitle', 'es', 'Proporcionamos la experiencia completa de regatas de yates con orientación profesional, equipo premium y recuerdos que duran toda la vida.', 'home_page'),
('home.features.subtitle', 'pl', 'Zapewniamy kompletne doświadczenie wyścigów jachtowych z profesjonalnym przewodnictwem, najwyższej jakości sprzętem i wspomnieniami, które trwają całe życie.', 'home_page'),
('home.features.subtitle', 'he', 'אנו מספקים את חוויית מירוץ היאכטות המלאה עם הדרכה מקצועית, ציוד פרימיום וזכרונות שנמשכים לכל החיים.', 'home_page'),
('home.features.subtitle', 'ru', 'Мы предоставляем полный опыт парусных гонок с профессиональным руководством, первоклассным оборудованием и воспоминаниями на всю жизнь.', 'home_page'),

-- Feature items
('home.feature.racing.title', 'en', 'Real Racing Format', 'home_page'),
('home.feature.racing.title', 'de', 'Echtes Rennformat', 'home_page'),
('home.feature.racing.title', 'fr', 'Format de course réel', 'home_page'),
('home.feature.racing.title', 'it', 'Formato di regata reale', 'home_page'),
('home.feature.racing.title', 'es', 'Formato de regata real', 'home_page'),
('home.feature.racing.title', 'pl', 'Prawdziwy format wyścigowy', 'home_page'),
('home.feature.racing.title', 'he', 'פורמט מירוץ אמיתי', 'home_page'),
('home.feature.racing.title', 'ru', 'Настоящий гоночный формат', 'home_page'),

('home.feature.racing.desc', 'en', 'Authentic yacht regatta with team dynamics, medals, and true competition.', 'home_page'),
('home.feature.racing.desc', 'de', 'Authentische Yachtregatta mit Teamdynamik, Medaillen und echtem Wettbewerb.', 'home_page'),
('home.feature.racing.desc', 'fr', 'Régate de yacht authentique avec dynamique d''équipe, médailles et vraie compétition.', 'home_page'),
('home.feature.racing.desc', 'it', 'Regata velica autentica con dinamiche di squadra, medaglie e vera competizione.', 'home_page'),
('home.feature.racing.desc', 'es', 'Regata de yates auténtica con dinámica de equipo, medallas y competencia real.', 'home_page'),
('home.feature.racing.desc', 'pl', 'Autentyczna regata jachtowa z dynamiką zespołu, medalami i prawdziwą rywalizacją.', 'home_page'),
('home.feature.racing.desc', 'he', 'רגטת יאכטות אותנטית עם דינמיקה קבוצתית, מדליות ותחרות אמיתית.', 'home_page'),
('home.feature.racing.desc', 'ru', 'Настоящая яхтенная регата с командной динамикой, медалями и настоящим соревнованием.', 'home_page'),

('home.feature.skipper.title', 'en', 'Professional Skipper', 'home_page'),
('home.feature.skipper.title', 'de', 'Professioneller Skipper', 'home_page'),
('home.feature.skipper.title', 'fr', 'Skipper professionnel', 'home_page'),
('home.feature.skipper.title', 'it', 'Skipper professionista', 'home_page'),
('home.feature.skipper.title', 'es', 'Patrón profesional', 'home_page'),
('home.feature.skipper.title', 'pl', 'Profesjonalny sternik', 'home_page'),
('home.feature.skipper.title', 'he', 'סקיפר מקצועי', 'home_page'),
('home.feature.skipper.title', 'ru', 'Профессиональный шкипер', 'home_page'),

('home.feature.skipper.desc', 'en', 'Certified and experienced sailing captains on every boat.', 'home_page'),
('home.feature.skipper.desc', 'de', 'Zertifizierte und erfahrene Segelkapitäne auf jedem Boot.', 'home_page'),
('home.feature.skipper.desc', 'fr', 'Capitaines de voile certifiés et expérimentés sur chaque bateau.', 'home_page'),
('home.feature.skipper.desc', 'it', 'Capitani di vela certificati ed esperti su ogni barca.', 'home_page'),
('home.feature.skipper.desc', 'es', 'Capitanes de vela certificados y experimentados en cada barco.', 'home_page'),
('home.feature.skipper.desc', 'pl', 'Certyfikowani i doświadczeni kapitanowie żeglarscy na każdej łodzi.', 'home_page'),
('home.feature.skipper.desc', 'he', 'רבי חובלים מוסמכים ומנוסים בכל סירה.', 'home_page'),
('home.feature.skipper.desc', 'ru', 'Сертифицированные и опытные капитаны на каждой лодке.', 'home_page'),

('home.feature.photo.title', 'en', 'Photo & Video', 'home_page'),
('home.feature.photo.title', 'de', 'Foto & Video', 'home_page'),
('home.feature.photo.title', 'fr', 'Photo et vidéo', 'home_page'),
('home.feature.photo.title', 'it', 'Foto e video', 'home_page'),
('home.feature.photo.title', 'es', 'Foto y video', 'home_page'),
('home.feature.photo.title', 'pl', 'Zdjęcia i wideo', 'home_page'),
('home.feature.photo.title', 'he', 'צילום ווידאו', 'home_page'),
('home.feature.photo.title', 'ru', 'Фото и видео', 'home_page'),

('home.feature.photo.desc', 'en', 'Professional photos and videos of your race day to remember and share.', 'home_page'),
('home.feature.photo.desc', 'de', 'Professionelle Fotos und Videos Ihres Renntages zum Erinnern und Teilen.', 'home_page'),
('home.feature.photo.desc', 'fr', 'Photos et vidéos professionnelles de votre journée de course à retenir et à partager.', 'home_page'),
('home.feature.photo.desc', 'it', 'Foto e video professionali della tua giornata di regata da ricordare e condividere.', 'home_page'),
('home.feature.photo.desc', 'es', 'Fotos y videos profesionales de tu día de regata para recordar y compartir.', 'home_page'),
('home.feature.photo.desc', 'pl', 'Profesjonalne zdjęcia i filmy z dnia wyścigu, które możesz zapamiętać i udostępnić.', 'home_page'),
('home.feature.photo.desc', 'he', 'תמונות וסרטונים מקצועיים של יום המירוץ שלך לזכור ולשתף.', 'home_page'),
('home.feature.photo.desc', 'ru', 'Профессиональные фотографии и видео вашего гоночного дня, которыми можно поделиться.', 'home_page'),

('home.feature.insured.title', 'en', 'Fully Insured', 'home_page'),
('home.feature.insured.title', 'de', 'Vollständig versichert', 'home_page'),
('home.feature.insured.title', 'fr', 'Entièrement assuré', 'home_page'),
('home.feature.insured.title', 'it', 'Completamente assicurato', 'home_page'),
('home.feature.insured.title', 'es', 'Totalmente asegurado', 'home_page'),
('home.feature.insured.title', 'pl', 'W pełni ubezpieczone', 'home_page'),
('home.feature.insured.title', 'he', 'מבוטח באופן מלא', 'home_page'),
('home.feature.insured.title', 'ru', 'Полностью застраховано', 'home_page'),

('home.feature.insured.desc', 'en', 'Complete safety coverage and modern equipment included.', 'home_page'),
('home.feature.insured.desc', 'de', 'Vollständiger Sicherheitsschutz und moderne Ausrüstung inbegriffen.', 'home_page'),
('home.feature.insured.desc', 'fr', 'Couverture de sécurité complète et équipement moderne inclus.', 'home_page'),
('home.feature.insured.desc', 'it', 'Copertura di sicurezza completa e attrezzature moderne incluse.', 'home_page'),
('home.feature.insured.desc', 'es', 'Cobertura de seguridad completa y equipo moderno incluido.', 'home_page'),
('home.feature.insured.desc', 'pl', 'Pełne ubezpieczenie i nowoczesny sprzęt w zestawie.', 'home_page'),
('home.feature.insured.desc', 'he', 'כיסוי בטיחות מלא וציוד מודרני כלולים.', 'home_page'),
('home.feature.insured.desc', 'ru', 'Полное страховое покрытие и современное оборудование включены.', 'home_page'),

('home.feature.premium.title', 'en', 'Accessible & Premium', 'home_page'),
('home.feature.premium.title', 'de', 'Zugänglich & Premium', 'home_page'),
('home.feature.premium.title', 'fr', 'Accessible et Premium', 'home_page'),
('home.feature.premium.title', 'it', 'Accessibile e Premium', 'home_page'),
('home.feature.premium.title', 'es', 'Accesible y Premium', 'home_page'),
('home.feature.premium.title', 'pl', 'Dostępne i Premium', 'home_page'),
('home.feature.premium.title', 'he', 'נגיש ופרימיום', 'home_page'),
('home.feature.premium.title', 'ru', 'Доступно и Премиум', 'home_page'),

('home.feature.premium.desc', 'en', 'A top-level regatta experience open to everyone — no experience needed.', 'home_page'),
('home.feature.premium.desc', 'de', 'Ein erstklassiges Regatta-Erlebnis für jeden — keine Erfahrung nötig.', 'home_page'),
('home.feature.premium.desc', 'fr', 'Une expérience de régate de haut niveau ouverte à tous — aucune expérience nécessaire.', 'home_page'),
('home.feature.premium.desc', 'it', 'Un''esperienza di regata di alto livello aperta a tutti — nessuna esperienza necessaria.', 'home_page'),
('home.feature.premium.desc', 'es', 'Una experiencia de regata de alto nivel abierta a todos — no se necesita experiencia.', 'home_page'),
('home.feature.premium.desc', 'pl', 'Doświadczenie regat na najwyższym poziomie dostępne dla wszystkich — nie jest wymagane doświadczenie.', 'home_page'),
('home.feature.premium.desc', 'he', 'חוויית רגטה ברמה גבוהה פתוחה לכולם — לא נדרש ניסיון.', 'home_page'),
('home.feature.premium.desc', 'ru', 'Регата высшего уровня, доступная для всех — опыт не требуется.', 'home_page'),

-- Experience Section
('home.experience.title', 'en', 'Your Perfect Day on Lake Garda', 'home_page'),
('home.experience.title', 'de', 'Ihr perfekter Tag am Gardasee', 'home_page'),
('home.experience.title', 'fr', 'Votre journée parfaite sur le lac de Garde', 'home_page'),
('home.experience.title', 'it', 'La tua giornata perfetta sul Lago di Garda', 'home_page'),
('home.experience.title', 'es', 'Tu día perfecto en el Lago de Garda', 'home_page'),
('home.experience.title', 'pl', 'Twój idealny dzień nad jeziorem Garda', 'home_page'),
('home.experience.title', 'he', 'היום המושלם שלך באגם גארדה', 'home_page'),
('home.experience.title', 'ru', 'Ваш идеальный день на озере Гарда', 'home_page'),

('home.experience.step1.title', 'en', 'Morning Briefing', 'home_page'),
('home.experience.step1.title', 'de', 'Morgenbesprechung', 'home_page'),
('home.experience.step1.title', 'fr', 'Briefing du matin', 'home_page'),
('home.experience.step1.title', 'it', 'Briefing mattutino', 'home_page'),
('home.experience.step1.title', 'es', 'Briefing matutino', 'home_page'),
('home.experience.step1.title', 'pl', 'Poranna odprawa', 'home_page'),
('home.experience.step1.title', 'he', 'תדרוך בוקר', 'home_page'),
('home.experience.step1.title', 'ru', 'Утренний брифинг', 'home_page'),

('home.experience.step1.desc', 'en', 'Meet your professional skipper and learn the basics of yacht racing in a relaxed, friendly environment.', 'home_page'),
('home.experience.step1.desc', 'de', 'Treffen Sie Ihren professionellen Skipper und lernen Sie die Grundlagen des Yachtrennsports in einer entspannten, freundlichen Umgebung.', 'home_page'),
('home.experience.step1.desc', 'fr', 'Rencontrez votre skipper professionnel et apprenez les bases de la course de yachts dans un environnement détendu et convivial.', 'home_page'),
('home.experience.step1.desc', 'it', 'Incontra il tuo skipper professionista e impara le basi delle regate veliche in un ambiente rilassato e amichevole.', 'home_page'),
('home.experience.step1.desc', 'es', 'Conoce a tu patrón profesional y aprende los conceptos básicos de las regatas de yates en un ambiente relajado y amigable.', 'home_page'),
('home.experience.step1.desc', 'pl', 'Spotkaj swojego profesjonalnego sternika i naucz się podstaw wyścigów jachtowych w zrelaksowanym, przyjaznym środowisku.', 'home_page'),
('home.experience.step1.desc', 'he', 'פגוש את הסקיפר המקצועי שלך ולמד את יסודות מירוצי היאכטות בסביבה רגועה וידידותית.', 'home_page'),
('home.experience.step1.desc', 'ru', 'Встретьтесь с профессиональным шкипером и изучите основы парусных гонок в расслабленной, дружественной обстановке.', 'home_page'),

('home.experience.step2.title', 'en', 'Racing Experience', 'home_page'),
('home.experience.step2.title', 'de', 'Rennerlebnis', 'home_page'),
('home.experience.step2.title', 'fr', 'Expérience de course', 'home_page'),
('home.experience.step2.title', 'it', 'Esperienza di regata', 'home_page'),
('home.experience.step2.title', 'es', 'Experiencia de regata', 'home_page'),
('home.experience.step2.title', 'pl', 'Doświadczenie wyścigowe', 'home_page'),
('home.experience.step2.title', 'he', 'חוויית מירוץ', 'home_page'),
('home.experience.step2.title', 'ru', 'Гоночный опыт', 'home_page'),

('home.experience.step2.desc', 'en', 'Participate in authentic yacht races with other boats, experiencing the thrill of competition on beautiful Lake Garda.', 'home_page'),
('home.experience.step2.desc', 'de', 'Nehmen Sie an authentischen Yachtrennen mit anderen Booten teil und erleben Sie den Nervenkitzel des Wettbewerbs auf dem wunderschönen Gardasee.', 'home_page'),
('home.experience.step2.desc', 'fr', 'Participez à d''authentiques courses de yachts avec d''autres bateaux, en vivant le frisson de la compétition sur le magnifique lac de Garde.', 'home_page'),
('home.experience.step2.desc', 'it', 'Partecipa a autentiche regate veliche con altre barche, sperimentando l''emozione della competizione sul bellissimo Lago di Garda.', 'home_page'),
('home.experience.step2.desc', 'es', 'Participa en auténticas regatas de yates con otros barcos, experimentando la emoción de la competencia en el hermoso Lago de Garda.', 'home_page'),
('home.experience.step2.desc', 'pl', 'Weź udział w autentycznych wyścigach jachtowych z innymi łodziami, doświadczając emocji związanych z rywalizacją na pięknym jeziorze Garda.', 'home_page'),
('home.experience.step2.desc', 'he', 'השתתף במירוצי יאכטות אותנטיים עם סירות אחרות, חווה את הריגוש של התחרות על אגם גארדה היפה.', 'home_page'),
('home.experience.step2.desc', 'ru', 'Участвуйте в настоящих парусных гонках с другими лодками, испытывая азарт соревнований на прекрасном озере Гарда.', 'home_page'),

('home.experience.step3.title', 'en', 'Medal Ceremony', 'home_page'),
('home.experience.step3.title', 'de', 'Medaillenzeremonie', 'home_page'),
('home.experience.step3.title', 'fr', 'Cérémonie de médailles', 'home_page'),
('home.experience.step3.title', 'it', 'Cerimonia di premiazione', 'home_page'),
('home.experience.step3.title', 'es', 'Ceremonia de medallas', 'home_page'),
('home.experience.step3.title', 'pl', 'Ceremonia medalowa', 'home_page'),
('home.experience.step3.title', 'he', 'טקס מדליות', 'home_page'),
('home.experience.step3.title', 'ru', 'Церемония награждения', 'home_page'),

('home.experience.step3.desc', 'en', 'Celebrate your achievement with an official medal ceremony and receive your personalized racing certificate.', 'home_page'),
('home.experience.step3.desc', 'de', 'Feiern Sie Ihren Erfolg mit einer offiziellen Medaillenzeremonie und erhalten Sie Ihr personalisiertes Rennzertifikat.', 'home_page'),
('home.experience.step3.desc', 'fr', 'Célébrez votre réussite avec une cérémonie officielle de remise des médailles et recevez votre certificat de course personnalisé.', 'home_page'),
('home.experience.step3.desc', 'it', 'Celebra il tuo successo con una cerimonia ufficiale di premiazione e ricevi il tuo certificato di regata personalizzato.', 'home_page'),
('home.experience.step3.desc', 'es', 'Celebra tu logro con una ceremonia oficial de medallas y recibe tu certificado de regata personalizado.', 'home_page'),
('home.experience.step3.desc', 'pl', 'Świętuj swoje osiągnięcie podczas oficjalnej ceremonii medalowej i otrzymaj spersonalizowany certyfikat wyścigowy.', 'home_page'),
('home.experience.step3.desc', 'he', 'חגוג את ההישג שלך עם טקס מדליות רשמי וקבל את תעודת המירוץ המותאמת אישית שלך.', 'home_page'),
('home.experience.step3.desc', 'ru', 'Отпразднуйте свое достижение официальной церемонией награждения и получите персонализированный гоночный сертификат.', 'home_page'),

('home.experience.cta', 'en', 'Learn More About the Experience', 'home_page'),
('home.experience.cta', 'de', 'Erfahren Sie mehr über das Erlebnis', 'home_page'),
('home.experience.cta', 'fr', 'En savoir plus sur l''expérience', 'home_page'),
('home.experience.cta', 'it', 'Scopri di più sull''esperienza', 'home_page'),
('home.experience.cta', 'es', 'Más información sobre la experiencia', 'home_page'),
('home.experience.cta', 'pl', 'Dowiedz się więcej o doświadczeniu', 'home_page'),
('home.experience.cta', 'he', 'למד עוד על החוויה', 'home_page'),
('home.experience.cta', 'ru', 'Узнать больше о программе', 'home_page'),

-- Testimonials Section
('home.testimonials.title', 'en', 'What Our Sailors Say', 'home_page'),
('home.testimonials.title', 'de', 'Was unsere Segler sagen', 'home_page'),
('home.testimonials.title', 'fr', 'Ce que disent nos marins', 'home_page'),
('home.testimonials.title', 'it', 'Cosa dicono i nostri velisti', 'home_page'),
('home.testimonials.title', 'es', 'Lo que dicen nuestros navegantes', 'home_page'),
('home.testimonials.title', 'pl', 'Co mówią nasi żeglarze', 'home_page'),
('home.testimonials.title', 'he', 'מה אומרים המפליגים שלנו', 'home_page'),
('home.testimonials.title', 'ru', 'Что говорят наши яхтсмены', 'home_page'),

('home.testimonials.subtitle', 'en', 'Join thousands of satisfied customers who''ve experienced the magic of Lake Garda racing', 'home_page'),
('home.testimonials.subtitle', 'de', 'Schließen Sie sich Tausenden zufriedener Kunden an, die die Magie des Gardasee-Rennsports erlebt haben', 'home_page'),
('home.testimonials.subtitle', 'fr', 'Rejoignez des milliers de clients satisfaits qui ont vécu la magie des courses sur le lac de Garde', 'home_page'),
('home.testimonials.subtitle', 'it', 'Unisciti a migliaia di clienti soddisfatti che hanno vissuto la magia delle regate sul Lago di Garda', 'home_page'),
('home.testimonials.subtitle', 'es', 'Únete a miles de clientes satisfechos que han experimentado la magia de las regatas en el Lago de Garda', 'home_page'),
('home.testimonials.subtitle', 'pl', 'Dołącz do tysięcy zadowolonych klientów, którzy doświadczyli magii wyścigów na jeziorze Garda', 'home_page'),
('home.testimonials.subtitle', 'he', 'הצטרף לאלפי לקוחות מרוצים שחוו את הקסם של מירוצי אגם גארדה', 'home_page'),
('home.testimonials.subtitle', 'ru', 'Присоединяйтесь к тысячам довольных клиентов, которые испытали магию гонок на озере Гарда', 'home_page'),

-- Location Section
('home.location.title', 'en', 'Prime Location in Riva del Garda', 'home_page'),
('home.location.title', 'de', 'Erstklassige Lage in Riva del Garda', 'home_page'),
('home.location.title', 'fr', 'Emplacement privilégié à Riva del Garda', 'home_page'),
('home.location.title', 'it', 'Posizione privilegiata a Riva del Garda', 'home_page'),
('home.location.title', 'es', 'Ubicación privilegiada en Riva del Garda', 'home_page'),
('home.location.title', 'pl', 'Doskonała lokalizacja w Riva del Garda', 'home_page'),
('home.location.title', 'he', 'מיקום מעולה בריבה דל גארדה', 'home_page'),
('home.location.title', 'ru', 'Отличное расположение в Рива-дель-Гарда', 'home_page'),

('home.location.access.title', 'en', 'Easy Access from Munich', 'home_page'),
('home.location.access.title', 'de', 'Einfacher Zugang von München', 'home_page'),
('home.location.access.title', 'fr', 'Accès facile depuis Munich', 'home_page'),
('home.location.access.title', 'it', 'Facile accesso da Monaco', 'home_page'),
('home.location.access.title', 'es', 'Fácil acceso desde Múnich', 'home_page'),
('home.location.access.title', 'pl', 'Łatwy dostęp z Monachium', 'home_page'),
('home.location.access.title', 'he', 'גישה נוחה ממינכן', 'home_page'),
('home.location.access.title', 'ru', 'Легкий доступ из Мюнхена', 'home_page'),

('home.location.access.desc', 'en', 'Just 4 hours drive from Munich, making it perfect for weekend getaways and corporate events.', 'home_page'),
('home.location.access.desc', 'de', 'Nur 4 Stunden Fahrt von München entfernt, ideal für Wochenendausflüge und Firmenveranstaltungen.', 'home_page'),
('home.location.access.desc', 'fr', 'À seulement 4 heures de route de Munich, ce qui en fait un endroit idéal pour les escapades de week-end et les événements d''entreprise.', 'home_page'),
('home.location.access.desc', 'it', 'A sole 4 ore di auto da Monaco, perfetto per fughe di fine settimana ed eventi aziendali.', 'home_page'),
('home.location.access.desc', 'es', 'A solo 4 horas en coche desde Múnich, lo que lo hace perfecto para escapadas de fin de semana y eventos corporativos.', 'home_page'),
('home.location.access.desc', 'pl', 'Tylko 4 godziny jazdy z Monachium, co czyni go idealnym na weekendowe wypady i imprezy firmowe.', 'home_page'),
('home.location.access.desc', 'he', 'רק 4 שעות נסיעה ממינכן, מה שהופך אותו למושלם לבריחות סוף שבוע ואירועים תאגידיים.', 'home_page'),
('home.location.access.desc', 'ru', 'Всего в 4 часах езды от Мюнхена, что делает его идеальным для выходных и корпоративных мероприятий.', 'home_page'),

('home.location.conditions.title', 'en', 'World-Class Sailing Conditions', 'home_page'),
('home.location.conditions.title', 'de', 'Weltklasse-Segelbedingungen', 'home_page'),
('home.location.conditions.title', 'fr', 'Conditions de navigation de classe mondiale', 'home_page'),
('home.location.conditions.title', 'it', 'Condizioni di vela di livello mondiale', 'home_page'),
('home.location.conditions.title', 'es', 'Condiciones de navegación de clase mundial', 'home_page'),
('home.location.conditions.title', 'pl', 'Światowej klasy warunki żeglarskie', 'home_page'),
('home.location.conditions.title', 'he', 'תנאי שיט ברמה עולמית', 'home_page'),
('home.location.conditions.title', 'ru', 'Условия для парусного спорта мирового класса', 'home_page'),

('home.location.conditions.desc', 'en', 'Lake Garda offers consistent winds and stunning Alpine scenery, making it Europe''s premier sailing destination.', 'home_page'),
('home.location.conditions.desc', 'de', 'Der Gardasee bietet beständige Winde und eine atemberaubende Alpenlandschaft, was ihn zum führenden Segelziel Europas macht.', 'home_page'),
('home.location.conditions.desc', 'fr', 'Le lac de Garde offre des vents constants et de magnifiques paysages alpins, ce qui en fait la première destination de voile d''Europe.', 'home_page'),
('home.location.conditions.desc', 'it', 'Il Lago di Garda offre venti costanti e splendidi paesaggi alpini, rendendolo la principale destinazione velica d''Europa.', 'home_page'),
('home.location.conditions.desc', 'es', 'El Lago de Garda ofrece vientos constantes y un impresionante paisaje alpino, lo que lo convierte en el principal destino de navegación de Europa.', 'home_page'),
('home.location.conditions.desc', 'pl', 'Jezioro Garda oferuje stałe wiatry i oszałamiające alpejskie krajobrazy, co czyni je najlepszym miejscem do żeglowania w Europie.', 'home_page'),
('home.location.conditions.desc', 'he', 'אגם גארדה מציע רוחות עקביות ונוף אלפיני מדהים, מה שהופך אותו ליעד השיט המוביל באירופה.', 'home_page'),
('home.location.conditions.desc', 'ru', 'Озеро Гарда предлагает постоянные ветра и потрясающие альпийские пейзажи, что делает его главным направлением для парусного спорта в Европе.', 'home_page'),

('home.location.departures.title', 'en', 'Daily Departures', 'home_page'),
('home.location.departures.title', 'de', 'Tägliche Abfahrten', 'home_page'),
('home.location.departures.title', 'fr', 'Départs quotidiens', 'home_page'),
('home.location.departures.title', 'it', 'Partenze giornaliere', 'home_page'),
('home.location.departures.title', 'es', 'Salidas diarias', 'home_page'),
('home.location.departures.title', 'pl', 'Codzienne wyjazdy', 'home_page'),
('home.location.departures.title', 'he', 'יציאות יומיות', 'home_page'),
('home.location.departures.title', 'ru', 'Ежедневные отправления', 'home_page'),

('home.location.departures.desc', 'en', 'Multiple time slots available daily from March to October, with flexible booking options.', 'home_page'),
('home.location.departures.desc', 'de', 'Mehrere Zeitfenster täglich von März bis Oktober verfügbar, mit flexiblen Buchungsoptionen.', 'home_page'),
('home.location.departures.desc', 'fr', 'Plusieurs créneaux horaires disponibles quotidiennement de mars à octobre, avec des options de réservation flexibles.', 'home_page'),
('home.location.departures.desc', 'it', 'Più fasce orarie disponibili ogni giorno da marzo a ottobre, con opzioni di prenotazione flessibili.', 'home_page'),
('home.location.departures.desc', 'es', 'Múltiples horarios disponibles diariamente de marzo a octubre, con opciones de reserva flexibles.', 'home_page'),
('home.location.departures.desc', 'pl', 'Wiele przedziałów czasowych dostępnych codziennie od marca do października, z elastycznymi opcjami rezerwacji.', 'home_page'),
('home.location.departures.desc', 'he', 'מספר משבצות זמן זמינות מדי יום ממרץ עד אוקטובר, עם אפשרויות הזמנה גמישות.', 'home_page'),
('home.location.departures.desc', 'ru', 'Несколько временных интервалов доступны ежедневно с марта по октябрь, с гибкими вариантами бронирования.', 'home_page'),

-- Partners Section
('home.partners.title', 'en', 'Our Trusted Partners', 'home_page'),
('home.partners.title', 'de', 'Unsere vertrauenswürdigen Partner', 'home_page'),
('home.partners.title', 'fr', 'Nos partenaires de confiance', 'home_page'),
('home.partners.title', 'it', 'I nostri partner fidati', 'home_page'),
('home.partners.title', 'es', 'Nuestros socios de confianza', 'home_page'),
('home.partners.title', 'pl', 'Nasi zaufani partnerzy', 'home_page'),
('home.partners.title', 'he', 'השותפים האמינים שלנו', 'home_page'),
('home.partners.title', 'ru', 'Наши надежные партнеры', 'home_page'),

('home.partners.subtitle', 'en', 'We work with the world''s leading yacht and marine equipment manufacturers to provide you with the best possible sailing experience.', 'home_page'),
('home.partners.subtitle', 'de', 'Wir arbeiten mit den weltweit führenden Yacht- und Marineausrüstungsherstellern zusammen, um Ihnen das bestmögliche Segelerlebnis zu bieten.', 'home_page'),
('home.partners.subtitle', 'fr', 'Nous travaillons avec les principaux fabricants mondiaux de yachts et d''équipements marins pour vous offrir la meilleure expérience de voile possible.', 'home_page'),
('home.partners.subtitle', 'it', 'Lavoriamo con i principali produttori mondiali di yacht e attrezzature marine per offrirti la migliore esperienza di vela possibile.', 'home_page'),
('home.partners.subtitle', 'es', 'Trabajamos con los principales fabricantes mundiales de yates y equipos marinos para brindarte la mejor experiencia de navegación posible.', 'home_page'),
('home.partners.subtitle', 'pl', 'Współpracujemy z wiodącymi na świecie producentami jachtów i sprzętu morskiego, aby zapewnić Ci najlepsze możliwe doświadczenie żeglarskie.', 'home_page'),
('home.partners.subtitle', 'he', 'אנו עובדים עם יצרני היאכטות וציוד הימי המובילים בעולם כדי לספק לך את חוויית השיט הטובה ביותר האפשרית.', 'home_page'),
('home.partners.subtitle', 'ru', 'Мы работаем с ведущими мировыми производителями яхт и морского оборудования, чтобы обеспечить вам наилучший опыт парусного спорта.', 'home_page'),

('home.partners.cta', 'en', 'Contact Us About Partnerships', 'home_page'),
('home.partners.cta', 'de', 'Kontaktieren Sie uns bezüglich Partnerschaften', 'home_page'),
('home.partners.cta', 'fr', 'Contactez-nous à propos des partenariats', 'home_page'),
('home.partners.cta', 'it', 'Contattaci per partnership', 'home_page'),
('home.partners.cta', 'es', 'Contáctanos sobre asociaciones', 'home_page'),
('home.partners.cta', 'pl', 'Skontaktuj się z nami w sprawie partnerstw', 'home_page'),
('home.partners.cta', 'he', 'צור קשר בנושא שותפויות', 'home_page'),
('home.partners.cta', 'ru', 'Свяжитесь с нами по вопросам партнерства', 'home_page'),

-- Final CTA Section
('home.cta.title', 'en', 'Ready for Your Sailing Adventure?', 'home_page'),
('home.cta.title', 'de', 'Bereit für Ihr Segelabenteuer?', 'home_page'),
('home.cta.title', 'fr', 'Prêt pour votre aventure de voile?', 'home_page'),
('home.cta.title', 'it', 'Pronto per la tua avventura velica?', 'home_page'),
('home.cta.title', 'es', '¿Listo para tu aventura de navegación?', 'home_page'),
('home.cta.title', 'pl', 'Gotowy na swoją przygodę żeglarską?', 'home_page'),
('home.cta.title', 'he', 'מוכן להרפתקת השיט שלך?', 'home_page'),
('home.cta.title', 'ru', 'Готовы к парусному приключению?', 'home_page'),

('home.cta.subtitle', 'en', 'Join us for an unforgettable day of yacht racing on Lake Garda. No experience necessary - just bring your sense of adventure!', 'home_page'),
('home.cta.subtitle', 'de', 'Begleiten Sie uns für einen unvergesslichen Tag des Yachtrennsports am Gardasee. Keine Erfahrung notwendig - bringen Sie einfach Ihren Abenteuersinn mit!', 'home_page'),
('home.cta.subtitle', 'fr', 'Rejoignez-nous pour une journée inoubliable de course de yachts sur le lac de Garde. Aucune expérience nécessaire - apportez simplement votre sens de l''aventure!', 'home_page'),
('home.cta.subtitle', 'it', 'Unisciti a noi per una giornata indimenticabile di regate veliche sul Lago di Garda. Nessuna esperienza necessaria - porta solo il tuo spirito d''avventura!', 'home_page'),
('home.cta.subtitle', 'es', 'Únete a nosotros para un día inolvidable de regatas de yates en el Lago de Garda. No se necesita experiencia, ¡solo trae tu sentido de aventura!', 'home_page'),
('home.cta.subtitle', 'pl', 'Dołącz do nas na niezapomniany dzień wyścigów jachtowych na jeziorze Garda. Doświadczenie nie jest konieczne - wystarczy zabrać ze sobą poczucie przygody!', 'home_page'),
('home.cta.subtitle', 'he', 'הצטרף אלינו ליום בלתי נשכח של מירוצי יאכטות באגם גארדה. לא נדרש ניסיון - פשוט הביאו את תחושת ההרפתקה שלכם!', 'home_page'),
('home.cta.subtitle', 'ru', 'Присоединяйтесь к нам для незабываемого дня парусных гонок на озере Гарда. Опыт не требуется - просто возьмите с собой чувство приключения!', 'home_page'),

('home.cta.button', 'en', 'Book Now - €195', 'home_page'),
('home.cta.button', 'de', 'Jetzt buchen - €195', 'home_page'),
('home.cta.button', 'fr', 'Réserver maintenant - €195', 'home_page'),
('home.cta.button', 'it', 'Prenota ora - €195', 'home_page'),
('home.cta.button', 'es', 'Reservar ahora - €195', 'home_page'),
('home.cta.button', 'pl', 'Zarezerwuj teraz - €195', 'home_page'),
('home.cta.button', 'he', 'הזמן עכשיו - €195', 'home_page'),
('home.cta.button', 'ru', 'Забронировать - €195', 'home_page')

ON CONFLICT (key, language_code) DO UPDATE SET
  text = EXCLUDED.text,
  category = EXCLUDED.category,
  updated_at = NOW();