-- Add translations for Events page tabs and sections
INSERT INTO translations (key, language_code, text, category) VALUES
-- Tabs
('events.tabs.overview', 'en', 'Overview', 'events_page'),
('events.tabs.overview', 'de', 'Übersicht', 'events_page'),
('events.tabs.overview', 'fr', 'Aperçu', 'events_page'),
('events.tabs.overview', 'it', 'Panoramica', 'events_page'),
('events.tabs.overview', 'es', 'Visión general', 'events_page'),
('events.tabs.overview', 'ru', 'Обзор', 'events_page'),

('events.tabs.schedule', 'en', 'Schedule', 'events_page'),
('events.tabs.schedule', 'de', 'Zeitplan', 'events_page'),
('events.tabs.schedule', 'fr', 'Programme', 'events_page'),
('events.tabs.schedule', 'it', 'Programma', 'events_page'),
('events.tabs.schedule', 'es', 'Horario', 'events_page'),
('events.tabs.schedule', 'ru', 'Расписание', 'events_page'),

('events.tabs.gallery', 'en', 'Gallery', 'events_page'),
('events.tabs.gallery', 'de', 'Galerie', 'events_page'),
('events.tabs.gallery', 'fr', 'Galerie', 'events_page'),
('events.tabs.gallery', 'it', 'Galleria', 'events_page'),
('events.tabs.gallery', 'es', 'Galería', 'events_page'),
('events.tabs.gallery', 'ru', 'Галерея', 'events_page'),

('events.tabs.weather', 'en', 'Weather', 'events_page'),
('events.tabs.weather', 'de', 'Wetter', 'events_page'),
('events.tabs.weather', 'fr', 'Météo', 'events_page'),
('events.tabs.weather', 'it', 'Meteo', 'events_page'),
('events.tabs.weather', 'es', 'Clima', 'events_page'),
('events.tabs.weather', 'ru', 'Погода', 'events_page'),

('events.tabs.equipment', 'en', 'Equipment', 'events_page'),
('events.tabs.equipment', 'de', 'Ausrüstung', 'events_page'),
('events.tabs.equipment', 'fr', 'Équipement', 'events_page'),
('events.tabs.equipment', 'it', 'Attrezzatura', 'events_page'),
('events.tabs.equipment', 'es', 'Equipamiento', 'events_page'),
('events.tabs.equipment', 'ru', 'Оборудование', 'events_page'),

('events.tabs.faq', 'en', 'FAQ', 'events_page'),
('events.tabs.faq', 'de', 'FAQ', 'events_page'),
('events.tabs.faq', 'fr', 'FAQ', 'events_page'),
('events.tabs.faq', 'it', 'FAQ', 'events_page'),
('events.tabs.faq', 'es', 'FAQ', 'events_page'),
('events.tabs.faq', 'ru', 'FAQ', 'events_page'),

-- Overview section
('events.overview.what_makes_special', 'en', 'What Makes Our Experience Special', 'events_page'),
('events.overview.what_makes_special', 'de', 'Was unser Erlebnis besonders macht', 'events_page'),
('events.overview.what_makes_special', 'fr', 'Ce qui rend notre expérience spéciale', 'events_page'),
('events.overview.what_makes_special', 'it', 'Cosa rende speciale la nostra esperienza', 'events_page'),
('events.overview.what_makes_special', 'es', 'Lo que hace especial nuestra experiencia', 'events_page'),
('events.overview.what_makes_special', 'ru', 'Что делает наш опыт особенным', 'events_page'),

('events.overview.professional_instruction', 'en', 'Certified sailing professionals with years of racing experience on Lake Garda.', 'events_page'),
('events.overview.professional_instruction', 'de', 'Zertifizierte Segelprofis mit jahrelanger Regattaerfahrung auf dem Gardasee.', 'events_page'),
('events.overview.professional_instruction', 'fr', 'Professionnels de la voile certifiés, avec des années d''expérience en régate sur le lac de Garde.', 'events_page'),
('events.overview.professional_instruction', 'it', 'Professionisti della vela certificati con anni di esperienza di regate sul Lago di Garda.', 'events_page'),
('events.overview.professional_instruction', 'es', 'Profesionales de la vela certificados con años de experiencia en regatas en el Lago de Garda.', 'events_page'),
('events.overview.professional_instruction', 'ru', 'Сертифицированные профессионалы с многолетним опытом участия в регатах на озере Гарда.', 'events_page'),

('events.overview.professional_instruction_desc', 'en', 'Learn from certified sailing professionals with years of racing experience on Lake Garda.', 'events_page'),
('events.overview.professional_instruction_desc', 'de', 'Lernen Sie von zertifizierten Segelprofis mit jahrelanger Rennerfahrung am Gardasee.', 'events_page'),
('events.overview.professional_instruction_desc', 'fr', 'Apprenez avec des professionnels certifiés ayant des années d''expérience en course sur le lac de Garde.', 'events_page'),
('events.overview.professional_instruction_desc', 'it', 'Impara da professionisti della vela certificati con anni di esperienza di regata sul Lago di Garda.', 'events_page'),
('events.overview.professional_instruction_desc', 'es', 'Aprende de profesionales certificados de vela con años de experiencia en regatas en el Lago de Garda.', 'events_page'),
('events.overview.professional_instruction_desc', 'ru', 'Учитесь у сертифицированных профессионалов парусного спорта с многолетним опытом гонок на озере Гарда.', 'events_page'),

('events.overview.authentic_racing', 'en', 'Authentic Racing', 'events_page'),
('events.overview.authentic_racing', 'de', 'Authentisches Rennen', 'events_page'),
('events.overview.authentic_racing', 'fr', 'Course authentique', 'events_page'),
('events.overview.authentic_racing', 'it', 'Regata autentica', 'events_page'),
('events.overview.authentic_racing', 'es', 'Carreras auténticas', 'events_page'),
('events.overview.authentic_racing', 'ru', 'Настоящие гонки', 'events_page'),

('events.overview.authentic_racing_desc', 'en', 'Participate in real yacht races with official timing, scoring, and medal ceremonies.', 'events_page'),
('events.overview.authentic_racing_desc', 'de', 'Nehmen Sie an echten Yachtrennen mit offizieller Zeitmessung, Wertung und Medaillenzeremonien teil.', 'events_page'),
('events.overview.authentic_racing_desc', 'fr', 'Participez à de véritables courses de yacht avec chronométrage officiel, notation et cérémonies de médailles.', 'events_page'),
('events.overview.authentic_racing_desc', 'it', 'Partecipa a vere regate di yacht con cronometraggio ufficiale, punteggio e cerimonie di premiazione.', 'events_page'),
('events.overview.authentic_racing_desc', 'es', 'Participa en regatas reales de yates con cronometraje oficial, puntuación y ceremonias de medallas.', 'events_page'),
('events.overview.authentic_racing_desc', 'ru', 'Участвуйте в настоящих яхтенных гонках с официальным хронометражем, подсчетом очков и церемониями награждения.', 'events_page'),

('events.overview.professional_documentation', 'en', 'Professional Documentation', 'events_page'),
('events.overview.professional_documentation', 'de', 'Professionelle Dokumentation', 'events_page'),
('events.overview.professional_documentation', 'fr', 'Documentation professionnelle', 'events_page'),
('events.overview.professional_documentation', 'it', 'Documentazione professionale', 'events_page'),
('events.overview.professional_documentation', 'es', 'Documentación profesional', 'events_page'),
('events.overview.professional_documentation', 'ru', 'Профессиональная документация', 'events_page'),

('events.overview.professional_documentation_desc', 'en', 'High-quality photos and videos of your experience, delivered within 24 hours.', 'events_page'),
('events.overview.professional_documentation_desc', 'de', 'Hochwertige Fotos und Videos Ihrer Erfahrung, geliefert innerhalb von 24 Stunden.', 'events_page'),
('events.overview.professional_documentation_desc', 'fr', 'Photos et vidéos de haute qualité de votre expérience, livrées sous 24 heures.', 'events_page'),
('events.overview.professional_documentation_desc', 'it', 'Foto e video di alta qualità della tua esperienza, consegnati entro 24 ore.', 'events_page'),
('events.overview.professional_documentation_desc', 'es', 'Fotos y videos de alta calidad de tu experiencia, entregados en 24 horas.', 'events_page'),
('events.overview.professional_documentation_desc', 'ru', 'Высококачественные фотографии и видео вашего опыта, доставляемые в течение 24 часов.', 'events_page'),

('events.overview.racing_format', 'en', 'Racing Format', 'events_page'),
('events.overview.racing_format', 'de', 'Rennformat', 'events_page'),
('events.overview.racing_format', 'fr', 'Format de course', 'events_page'),
('events.overview.racing_format', 'it', 'Formato di regata', 'events_page'),
('events.overview.racing_format', 'es', 'Formato de competición', 'events_page'),
('events.overview.racing_format', 'ru', 'Формат гонок', 'events_page'),

('events.overview.pro_level_regatta', 'en', 'Pro-Level One-Day Regatta', 'events_page'),
('events.overview.pro_level_regatta', 'de', 'Profi-Level Eintages-Regatta', 'events_page'),
('events.overview.pro_level_regatta', 'fr', 'Régate d''un jour de niveau pro', 'events_page'),
('events.overview.pro_level_regatta', 'it', 'Regata di un giorno di livello professionale', 'events_page'),
('events.overview.pro_level_regatta', 'es', 'Regata de un día de nivel profesional', 'events_page'),
('events.overview.pro_level_regatta', 'ru', 'Однодневная регата профессионального уровня', 'events_page'),

('events.overview.j70_yachts', 'en', 'Races held on J/70 class professional sailing yachts', 'events_page'),
('events.overview.j70_yachts', 'de', 'Rennen auf professionellen J/70-Klasse-Segelyachten', 'events_page'),
('events.overview.j70_yachts', 'fr', 'Courses organisées sur des yachts professionnels de classe J/70', 'events_page'),
('events.overview.j70_yachts', 'it', 'Regate tenute su yacht a vela professionali di classe J/70', 'events_page'),
('events.overview.j70_yachts', 'es', 'Regatas realizadas en yates de vela profesionales de clase J/70', 'events_page'),
('events.overview.j70_yachts', 'ru', 'Гонки проводятся на профессиональных парусных яхтах класса J/70', 'events_page'),

('events.overview.licensed_skipper', 'en', 'Each boat includes a licensed skipper and full crew', 'events_page'),
('events.overview.licensed_skipper', 'de', 'Jedes Boot beinhaltet einen lizenzierten Skipper und eine komplette Crew', 'events_page'),
('events.overview.licensed_skipper', 'fr', 'Chaque bateau comprend un skipper agréé et un équipage complet', 'events_page'),
('events.overview.licensed_skipper', 'it', 'Ogni barca include uno skipper con licenza e un equipaggio completo', 'events_page'),
('events.overview.licensed_skipper', 'es', 'Cada barco incluye un patrón con licencia y una tripulación completa', 'events_page'),
('events.overview.licensed_skipper', 'ru', 'Каждая лодка включает лицензированного шкипера и полный экипаж', 'events_page'),

('events.overview.official_races', 'en', '3–5 official races per day, scored under sailing sport rules', 'events_page'),
('events.overview.official_races', 'de', '3–5 offizielle Rennen pro Tag, gewertet nach Segelsportregeln', 'events_page'),
('events.overview.official_races', 'fr', '3 à 5 courses officielles par jour, notées selon les règles du sport nautique', 'events_page'),
('events.overview.official_races', 'it', '3-5 regate ufficiali al giorno, punteggiate secondo le regole dello sport velico', 'events_page'),
('events.overview.official_races', 'es', '3-5 regatas oficiales por día, puntuadas según las reglas del deporte de vela', 'events_page'),
('events.overview.official_races', 'ru', '3–5 официальных гонок в день, оцениваемых по правилам парусного спорта', 'events_page'),

('events.overview.judging_team', 'en', 'Supervised by a qualified judging team and technical support boats', 'events_page'),
('events.overview.judging_team', 'de', 'Beaufsichtigt von einem qualifizierten Schiedsrichterteam und technischen Supportbooten', 'events_page'),
('events.overview.judging_team', 'fr', 'Supervisé par une équipe de juges qualifiés et des bateaux de support technique', 'events_page'),
('events.overview.judging_team', 'it', 'Supervisionato da un team di giudici qualificati e barche di supporto tecnico', 'events_page'),
('events.overview.judging_team', 'es', 'Supervisado por un equipo de jueces calificados y barcos de apoyo técnico', 'events_page'),
('events.overview.judging_team', 'ru', 'Под наблюдением квалифицированной судейской команды и лодок технической поддержки', 'events_page'),

('events.overview.medal_ceremony_certificates', 'en', 'Medal ceremony and certificates for top crews', 'events_page'),
('events.overview.medal_ceremony_certificates', 'de', 'Medaillenzeremonie und Zertifikate für die besten Crews', 'events_page'),
('events.overview.medal_ceremony_certificates', 'fr', 'Cérémonie de remise des médailles et certificats pour les meilleurs équipages', 'events_page'),
('events.overview.medal_ceremony_certificates', 'it', 'Cerimonia delle medaglie e certificati per i migliori equipaggi', 'events_page'),
('events.overview.medal_ceremony_certificates', 'es', 'Ceremonia de medallas y certificados para las mejores tripulaciones', 'events_page'),
('events.overview.medal_ceremony_certificates', 'ru', 'Церемония награждения медалями и сертификаты для лучших экипажей', 'events_page'),

-- Services Page Translations
('services.corporate_regatta.title', 'en', '🧭 Corporate Sailing Regatta', 'services_page'),
('services.corporate_regatta.title', 'de', '🧭 Firmen-Segelregatta', 'services_page'),
('services.corporate_regatta.title', 'fr', '🧭 Régate de Voile d''Entreprise', 'services_page'),
('services.corporate_regatta.title', 'it', '🧭 Regata di Vela Aziendale', 'services_page'),
('services.corporate_regatta.title', 'es', '🧭 Regata Corporativa de Vela', 'services_page'),
('services.corporate_regatta.title', 'ru', '🧭 Корпоративная парусная регата', 'services_page'),

('services.corporate_regatta.description', 'en', 'We offer a unique team-building program through participation in a real sailing regatta. Strengthen team spirit and create unforgettable memories on Lake Garda.', 'services_page'),
('services.corporate_regatta.description', 'de', 'Wir bieten ein einzigartiges Teambuilding-Programm durch die Teilnahme an einer echten Segelregatta. Stärken Sie den Teamgeist und schaffen Sie unvergessliche Erinnerungen am Gardasee.', 'services_page'),
('services.corporate_regatta.description', 'fr', 'Nous proposons un programme unique de team-building par la participation à une vraie régate de voile. Renforcez l''esprit d''équipe et créez des souvenirs inoubliables sur le lac de Garde.', 'services_page'),
('services.corporate_regatta.description', 'it', 'Offriamo un programma unico di team building attraverso la partecipazione a una vera regata a vela. Rafforza lo spirito di squadra e crea ricordi indimenticabili sul Lago di Garda.', 'services_page'),
('services.corporate_regatta.description', 'es', 'Ofrecemos un programa único de construcción de equipos a través de la participación en una regata de vela real. Fortalece el espíritu de equipo y crea recuerdos inolvidables en el Lago de Garda.', 'services_page'),
('services.corporate_regatta.description', 'ru', 'Мы предлагаем уникальную программу тимбилдинга через участие в настоящей парусной регате. Укрепите командный дух и создайте незабываемые воспоминания на озере Гарда.', 'services_page'),

('services.corporate_regatta.learn_more', 'en', 'Learn more →', 'services_page'),
('services.corporate_regatta.learn_more', 'de', 'Mehr erfahren →', 'services_page'),
('services.corporate_regatta.learn_more', 'fr', 'En savoir plus →', 'services_page'),
('services.corporate_regatta.learn_more', 'it', 'Scopri di più →', 'services_page'),
('services.corporate_regatta.learn_more', 'es', 'Saber más →', 'services_page'),
('services.corporate_regatta.learn_more', 'ru', 'Узнать больше →', 'services_page'),

('services.gift_certificates.title', 'en', '🎁 Gift Certificates', 'services_page'),
('services.gift_certificates.title', 'de', '🎁 Geschenkgutscheine', 'services_page'),
('services.gift_certificates.title', 'fr', '🎁 Cartes Cadeaux', 'services_page'),
('services.gift_certificates.title', 'it', '🎁 Buoni Regalo', 'services_page'),
('services.gift_certificates.title', 'es', '🎁 Certificados de Regalo', 'services_page'),
('services.gift_certificates.title', 'ru', '🎁 Подарочные сертификаты', 'services_page'),

('services.gift_certificates.description', 'en', 'Perfect gift for sailing enthusiasts. Give the gift of an unforgettable yacht racing experience on beautiful Lake Garda.', 'services_page'),
('services.gift_certificates.description', 'de', 'Perfektes Geschenk für Segelenthusiasten. Schenken Sie das Erlebnis einer unvergesslichen Yachtregatta auf dem wunderschönen Gardasee.', 'services_page'),
('services.gift_certificates.description', 'fr', 'Cadeau parfait pour les amateurs de voile. Offrez le cadeau d''une expérience de régate inoubliable sur le magnifique lac de Garde.', 'services_page'),
('services.gift_certificates.description', 'it', 'Regalo perfetto per gli appassionati di vela. Regala l''esperienza di una indimenticabile regata in yacht sul bellissimo Lago di Garda.', 'services_page'),
('services.gift_certificates.description', 'es', 'Regalo perfecto para los entusiastas de la navegación. Regala la experiencia de una regata inolvidable en el hermoso Lago de Garda.', 'services_page'),
('services.gift_certificates.description', 'ru', 'Идеальный подарок для любителей парусного спорта. Подарите незабываемый опыт яхтенных гонок на прекрасном озере Гарда.', 'services_page'),

('services.gift_certificates.learn_more', 'en', 'Learn more →', 'services_page'),
('services.gift_certificates.learn_more', 'de', 'Mehr erfahren →', 'services_page'),
('services.gift_certificates.learn_more', 'fr', 'En savoir plus →', 'services_page'),
('services.gift_certificates.learn_more', 'it', 'Scopri di più →', 'services_page'),
('services.gift_certificates.learn_more', 'es', 'Saber más →', 'services_page'),
('services.gift_certificates.learn_more', 'ru', 'Узнать больше →', 'services_page'),

-- Gift Certificates Page Translations
('gift.title', 'en', 'Gift Certificates', 'gift_page'),
('gift.title', 'de', 'Geschenkgutscheine', 'gift_page'),
('gift.title', 'fr', 'Cartes Cadeaux', 'gift_page'),
('gift.title', 'it', 'Buoni Regalo', 'gift_page'),
('gift.title', 'es', 'Certificados de Regalo', 'gift_page'),
('gift.title', 'ru', 'Подарочные Сертификаты', 'gift_page'),

('gift.subtitle', 'en', 'Give the gift of adventure! Our yacht racing experiences on Lake Garda make perfect gifts for sailing enthusiasts and adventure seekers.', 'gift_page'),
('gift.subtitle', 'de', 'Verschenken Sie das Abenteuer! Unsere Yachtrennerlebnisse am Gardasee sind perfekte Geschenke für Segelenthusiasten und Abenteuersucher.', 'gift_page'),
('gift.subtitle', 'fr', 'Offrez le cadeau de l''aventure ! Nos expériences de régates sur le lac de Garde sont des cadeaux parfaits pour les amateurs de voile et les chercheurs d''aventure.', 'gift_page'),
('gift.subtitle', 'it', 'Regala l''avventura! Le nostre esperienze di regata sul Lago di Garda sono regali perfetti per gli appassionati di vela e i cercatori di avventure.', 'gift_page'),
('gift.subtitle', 'es', '¡Regala la aventura! Nuestras experiencias de regatas en el Lago de Garda son regalos perfectos para entusiastas de la vela y buscadores de aventuras.', 'gift_page'),
('gift.subtitle', 'ru', 'Подарите приключение! Наши гонки на яхтах на озере Гарда — идеальный подарок для любителей парусного спорта и искателей приключений.', 'gift_page'),

('gift.form.title', 'en', 'Create Your Gift Certificate', 'gift_page'),
('gift.form.title', 'de', 'Erstellen Sie Ihren Geschenkgutschein', 'gift_page'),
('gift.form.title', 'fr', 'Créez Votre Carte Cadeau', 'gift_page'),
('gift.form.title', 'it', 'Crea il Tuo Buono Regalo', 'gift_page'),
('gift.form.title', 'es', 'Crea Tu Certificado de Regalo', 'gift_page'),
('gift.form.title', 'ru', 'Создайте Свой Подарочный Сертификат', 'gift_page'),

('gift.form.amount', 'en', 'Select Amount', 'gift_page'),
('gift.form.amount', 'de', 'Betrag auswählen', 'gift_page'),
('gift.form.amount', 'fr', 'Sélectionner le Montant', 'gift_page'),
('gift.form.amount', 'it', 'Seleziona Importo', 'gift_page'),
('gift.form.amount', 'es', 'Seleccionar Monto', 'gift_page'),
('gift.form.amount', 'ru', 'Выбрать сумму', 'gift_page'),

('gift.form.recipient', 'en', 'Recipient Information', 'gift_page'),
('gift.form.recipient', 'de', 'Empfängerinformationen', 'gift_page'),
('gift.form.recipient', 'fr', 'Informations sur le Destinataire', 'gift_page'),
('gift.form.recipient', 'it', 'Informazioni sul Destinatario', 'gift_page'),
('gift.form.recipient', 'es', 'Información del Destinatario', 'gift_page'),
('gift.form.recipient', 'ru', 'Информация о получателе', 'gift_page'),

('gift.form.recipient_name', 'en', 'Recipient Name', 'gift_page'),
('gift.form.recipient_name', 'de', 'Name des Empfängers', 'gift_page'),
('gift.form.recipient_name', 'fr', 'Nom du Destinataire', 'gift_page'),
('gift.form.recipient_name', 'it', 'Nome del Destinatario', 'gift_page'),
('gift.form.recipient_name', 'es', 'Nombre del Destinatario', 'gift_page'),
('gift.form.recipient_name', 'ru', 'Имя получателя', 'gift_page'),

('gift.form.recipient_email', 'en', 'Recipient Email', 'gift_page'),
('gift.form.recipient_email', 'de', 'E-Mail des Empfängers', 'gift_page'),
('gift.form.recipient_email', 'fr', 'E-mail du Destinataire', 'gift_page'),
('gift.form.recipient_email', 'it', 'Email del Destinatario', 'gift_page'),
('gift.form.recipient_email', 'es', 'Correo Electrónico del Destinatario', 'gift_page'),
('gift.form.recipient_email', 'ru', 'Email получателя', 'gift_page'),

('gift.form.purchaser', 'en', 'Your Information', 'gift_page'),
('gift.form.purchaser', 'de', 'Ihre Informationen', 'gift_page'),
('gift.form.purchaser', 'fr', 'Vos Informations', 'gift_page'),
('gift.form.purchaser', 'it', 'Le Tue Informazioni', 'gift_page'),
('gift.form.purchaser', 'es', 'Tu Información', 'gift_page'),
('gift.form.purchaser', 'ru', 'Ваша информация', 'gift_page'),

('gift.form.your_name', 'en', 'Your Name', 'gift_page'),
('gift.form.your_name', 'de', 'Ihr Name', 'gift_page'),
('gift.form.your_name', 'fr', 'Votre Nom', 'gift_page'),
('gift.form.your_name', 'it', 'Il Tuo Nome', 'gift_page'),
('gift.form.your_name', 'es', 'Tu Nombre', 'gift_page'),
('gift.form.your_name', 'ru', 'Ваше имя', 'gift_page'),

('gift.form.your_email', 'en', 'Your Email', 'gift_page'),
('gift.form.your_email', 'de', 'Ihre E-Mail', 'gift_page'),
('gift.form.your_email', 'fr', 'Votre E-mail', 'gift_page'),
('gift.form.your_email', 'it', 'La Tua Email', 'gift_page'),
('gift.form.your_email', 'es', 'Tu Correo Electrónico', 'gift_page'),
('gift.form.your_email', 'ru', 'Ваш email', 'gift_page'),

('gift.form.message', 'en', 'Personal Message', 'gift_page'),
('gift.form.message', 'de', 'Persönliche Nachricht', 'gift_page'),
('gift.form.message', 'fr', 'Message Personnel', 'gift_page'),
('gift.form.message', 'it', 'Messaggio Personale', 'gift_page'),
('gift.form.message', 'es', 'Mensaje Personal', 'gift_page'),
('gift.form.message', 'ru', 'Личное сообщение', 'gift_page'),

('gift.form.optional', 'en', 'Optional', 'gift_page'),
('gift.form.optional', 'de', 'Optional', 'gift_page'),
('gift.form.optional', 'fr', 'Optionnel', 'gift_page'),
('gift.form.optional', 'it', 'Opzionale', 'gift_page'),
('gift.form.optional', 'es', 'Opcional', 'gift_page'),
('gift.form.optional', 'ru', 'Необязательно', 'gift_page'),

('gift.form.message_placeholder', 'en', 'Add a personal message to your gift...', 'gift_page'),
('gift.form.message_placeholder', 'de', 'Fügen Sie Ihrem Geschenk eine persönliche Nachricht hinzu...', 'gift_page'),
('gift.form.message_placeholder', 'fr', 'Ajoutez un message personnel à votre cadeau...', 'gift_page'),
('gift.form.message_placeholder', 'it', 'Aggiungi un messaggio personale al tuo regalo...', 'gift_page'),
('gift.form.message_placeholder', 'es', 'Añade un mensaje personal a tu regalo...', 'gift_page'),
('gift.form.message_placeholder', 'ru', 'Добавьте личное сообщение к вашему подарку...', 'gift_page'),

('gift.form.purchase', 'en', 'Purchase Gift Certificate', 'gift_page'),
('gift.form.purchase', 'de', 'Geschenkgutschein kaufen', 'gift_page'),
('gift.form.purchase', 'fr', 'Acheter une Carte Cadeau', 'gift_page'),
('gift.form.purchase', 'it', 'Acquista Buono Regalo', 'gift_page'),
('gift.form.purchase', 'es', 'Comprar Certificado de Regalo', 'gift_page'),
('gift.form.purchase', 'ru', 'Купить подарочный сертификат', 'gift_page'),

('gift.features.title', 'en', 'Perfect Gift for Any Occasion', 'gift_page'),
('gift.features.title', 'de', 'Perfektes Geschenk für jeden Anlass', 'gift_page'),
('gift.features.title', 'fr', 'Cadeau Parfait pour Toute Occasion', 'gift_page'),
('gift.features.title', 'it', 'Regalo Perfetto per Ogni Occasione', 'gift_page'),
('gift.features.title', 'es', 'Regalo Perfecto para Cualquier Ocasión', 'gift_page'),
('gift.features.title', 'ru', 'Идеальный подарок для любого случая', 'gift_page'),

('gift.features.romantic', 'en', 'Romantic getaways', 'gift_page'),
('gift.features.romantic', 'de', 'Romantische Ausflüge', 'gift_page'),
('gift.features.romantic', 'fr', 'Escapades romantiques', 'gift_page'),
('gift.features.romantic', 'it', 'Fughe romantiche', 'gift_page'),
('gift.features.romantic', 'es', 'Escapadas románticas', 'gift_page'),
('gift.features.romantic', 'ru', 'Романтические поездки', 'gift_page'),

('gift.features.birthdays', 'en', 'Birthdays & celebrations', 'gift_page'),
('gift.features.birthdays', 'de', 'Geburtstage & Feiern', 'gift_page'),
('gift.features.birthdays', 'fr', 'Anniversaires et célébrations', 'gift_page'),
('gift.features.birthdays', 'it', 'Compleanni e celebrazioni', 'gift_page'),
('gift.features.birthdays', 'es', 'Cumpleaños y celebraciones', 'gift_page'),
('gift.features.birthdays', 'ru', 'Дни рождения и праздники', 'gift_page'),

('gift.features.family', 'en', 'Family adventures', 'gift_page'),
('gift.features.family', 'de', 'Familienabenteuer', 'gift_page'),
('gift.features.family', 'fr', 'Aventures en famille', 'gift_page'),
('gift.features.family', 'it', 'Avventure familiari', 'gift_page'),
('gift.features.family', 'es', 'Aventuras familiares', 'gift_page'),
('gift.features.family', 'ru', 'Семейные приключения', 'gift_page'),

('gift.features.special', 'en', 'Special achievements', 'gift_page'),
('gift.features.special', 'de', 'Besondere Leistungen', 'gift_page'),
('gift.features.special', 'fr', 'Réalisations spéciales', 'gift_page'),
('gift.features.special', 'it', 'Traguardi speciali', 'gift_page'),
('gift.features.special', 'es', 'Logros especiales', 'gift_page'),
('gift.features.special', 'ru', 'Особые достижения', 'gift_page'),

('gift.how_it_works.title', 'en', 'How It Works', 'gift_page'),
('gift.how_it_works.title', 'de', 'Wie es funktioniert', 'gift_page'),
('gift.how_it_works.title', 'fr', 'Comment Ça Marche', 'gift_page'),
('gift.how_it_works.title', 'it', 'Come Funziona', 'gift_page'),
('gift.how_it_works.title', 'es', 'Cómo Funciona', 'gift_page'),
('gift.how_it_works.title', 'ru', 'Как это работает', 'gift_page'),

('gift.how_it_works.step1', 'en', 'Purchase Certificate', 'gift_page'),
('gift.how_it_works.step1', 'de', 'Zertifikat kaufen', 'gift_page'),
('gift.how_it_works.step1', 'fr', 'Acheter le Certificat', 'gift_page'),
('gift.how_it_works.step1', 'it', 'Acquista Certificato', 'gift_page'),
('gift.how_it_works.step1', 'es', 'Comprar Certificado', 'gift_page'),
('gift.how_it_works.step1', 'ru', 'Приобретите сертификат', 'gift_page'),

('gift.how_it_works.step1_desc', 'en', 'Choose amount and recipient details', 'gift_page'),
('gift.how_it_works.step1_desc', 'de', 'Wählen Sie Betrag und Empfängerdetails', 'gift_page'),
('gift.how_it_works.step1_desc', 'fr', 'Choisissez le montant et les détails du destinataire', 'gift_page'),
('gift.how_it_works.step1_desc', 'it', 'Scegli importo e dettagli del destinatario', 'gift_page'),
('gift.how_it_works.step1_desc', 'es', 'Elige la cantidad y los detalles del destinatario', 'gift_page'),
('gift.how_it_works.step1_desc', 'ru', 'Выберите сумму и данные получателя', 'gift_page'),

('gift.how_it_works.step2', 'en', 'Receive Certificate', 'gift_page'),
('gift.how_it_works.step2', 'de', 'Zertifikat erhalten', 'gift_page'),
('gift.how_it_works.step2', 'fr', 'Recevoir le Certificat', 'gift_page'),
('gift.how_it_works.step2', 'it', 'Ricevi Certificato', 'gift_page'),
('gift.how_it_works.step2', 'es', 'Recibir Certificado', 'gift_page'),
('gift.how_it_works.step2', 'ru', 'Получите сертификат', 'gift_page'),

('gift.how_it_works.step2_desc', 'en', 'Digital certificate sent via email', 'gift_page'),
('gift.how_it_works.step2_desc', 'de', 'Digitales Zertifikat per E-Mail gesendet', 'gift_page'),
('gift.how_it_works.step2_desc', 'fr', 'Certificat numérique envoyé par e-mail', 'gift_page'),
('gift.how_it_works.step2_desc', 'it', 'Certificato digitale inviato via email', 'gift_page'),
('gift.how_it_works.step2_desc', 'es', 'Certificado digital enviado por correo electrónico', 'gift_page'),
('gift.how_it_works.step2_desc', 'ru', 'Цифровой сертификат, отправленный по электронной почте', 'gift_page'),

('gift.how_it_works.step3', 'en', 'Book Experience', 'gift_page'),
('gift.how_it_works.step3', 'de', 'Erlebnis buchen', 'gift_page'),
('gift.how_it_works.step3', 'fr', 'Réserver l''Expérience', 'gift_page'),
('gift.how_it_works.step3', 'it', 'Prenota Esperienza', 'gift_page'),
('gift.how_it_works.step3', 'es', 'Reservar Experiencia', 'gift_page'),
('gift.how_it_works.step3', 'ru', 'Забронировать впечатление', 'gift_page'),

('gift.how_it_works.step3_desc', 'en', 'Recipient books their sailing adventure', 'gift_page'),
('gift.how_it_works.step3_desc', 'de', 'Empfänger bucht sein Segelabenteuer', 'gift_page'),
('gift.how_it_works.step3_desc', 'fr', 'Le destinataire réserve son aventure de voile', 'gift_page'),
('gift.how_it_works.step3_desc', 'it', 'Il destinatario prenota la sua avventura a vela', 'gift_page'),
('gift.how_it_works.step3_desc', 'es', 'El destinatario reserva su aventura de navegación', 'gift_page'),
('gift.how_it_works.step3_desc', 'ru', 'Получатель бронирует своё парусное приключение', 'gift_page'),

('gift.validity.title', 'en', 'Certificate Validity', 'gift_page'),
('gift.validity.title', 'de', 'Zertifikatsgültigkeit', 'gift_page'),
('gift.validity.title', 'fr', 'Validité du Certificat', 'gift_page'),
('gift.validity.title', 'it', 'Validità del Certificato', 'gift_page'),
('gift.validity.title', 'es', 'Validez del Certificado', 'gift_page'),
('gift.validity.title', 'ru', 'Срок действия сертификата', 'gift_page'),

('gift.validity.duration', 'en', 'Valid for 12 months from purchase date', 'gift_page'),
('gift.validity.duration', 'de', 'Gültig für 12 Monate ab Kaufdatum', 'gift_page'),
('gift.validity.duration', 'fr', 'Valable 12 mois à partir de la date d''achat', 'gift_page'),
('gift.validity.duration', 'it', 'Valido per 12 mesi dalla data di acquisto', 'gift_page'),
('gift.validity.duration', 'es', 'Válido por 12 meses desde la fecha de compra', 'gift_page'),
('gift.validity.duration', 'ru', 'Действителен в течение 12 месяцев с даты покупки', 'gift_page'),

('gift.validity.flexible', 'en', 'Flexible booking - no blackout dates', 'gift_page'),
('gift.validity.flexible', 'de', 'Flexible Buchung - keine Sperrdaten', 'gift_page'),
('gift.validity.flexible', 'fr', 'Réservation flexible - pas de dates d''interdiction', 'gift_page'),
('gift.validity.flexible', 'it', 'Prenotazione flessibile - nessuna data di blackout', 'gift_page'),
('gift.validity.flexible', 'es', 'Reserva flexible - sin fechas bloqueadas', 'gift_page'),
('gift.validity.flexible', 'ru', 'Гибкое бронирование - нет запрещенных дат', 'gift_page'),

-- Footer Translations
('footer.description', 'en', 'Experience the thrill of yacht racing on the world-famous Lake Garda. Professional instruction, premium equipment, and unforgettable memories.', 'footer'),
('footer.description', 'de', 'Erleben Sie den Nervenkitzel des Segelrennsports auf dem weltberühmten Gardasee. Professionelle Anleitung, erstklassige Ausrüstung und unvergessliche Erinnerungen.', 'footer'),
('footer.description', 'fr', 'Vivez l''émotion des courses de yacht sur le célèbre lac de Garde. Instruction professionnelle, équipement haut de gamme et souvenirs inoubliables.', 'footer'),
('footer.description', 'it', 'Vivi l''emozione delle regate in yacht sul famoso Lago di Garda. Istruzione professionale, attrezzature premium e ricordi indimenticabili.', 'footer'),
('footer.description', 'es', 'Experimenta la emoción de las regatas de yates en el mundialmente famoso Lago de Garda. Instrucción profesional, equipo de primera calidad y recuerdos inolvidables.', 'footer'),
('footer.description', 'ru', 'Испытайте волнение от яхтенных гонок на всемирно известном озере Гарда. Профессиональное обучение, первоклассное оборудование и незабываемые воспоминания.', 'footer'),

('footer.quick_links.title', 'en', 'Quick Links', 'footer'),
('footer.quick_links.title', 'de', 'Schnelllinks', 'footer'),
('footer.quick_links.title', 'fr', 'Liens Rapides', 'footer'),
('footer.quick_links.title', 'it', 'Link Rapidi', 'footer'),
('footer.quick_links.title', 'es', 'Enlaces Rápidos', 'footer'),
('footer.quick_links.title', 'ru', 'Быстрые ссылки', 'footer'),

('footer.links.privacy_policy', 'en', 'Privacy Policy', 'footer'),
('footer.links.privacy_policy', 'de', 'Datenschutzrichtlinie', 'footer'),
('footer.links.privacy_policy', 'fr', 'Politique de Confidentialité', 'footer'),
('footer.links.privacy_policy', 'it', 'Informativa sulla Privacy', 'footer'),
('footer.links.privacy_policy', 'es', 'Política de Privacidad', 'footer'),
('footer.links.privacy_policy', 'ru', 'Политика конфиденциальности', 'footer'),

('footer.links.terms_conditions', 'en', 'Terms & Conditions', 'footer'),
('footer.links.terms_conditions', 'de', 'Allgemeine Geschäftsbedingungen', 'footer'),
('footer.links.terms_conditions', 'fr', 'Termes et Conditions', 'footer'),
('footer.links.terms_conditions', 'it', 'Termini e Condizioni', 'footer'),
('footer.links.terms_conditions', 'es', 'Términos y Condiciones', 'footer'),
('footer.links.terms_conditions', 'ru', 'Условия использования', 'footer'),

('footer.links.cancellation_policy', 'en', 'Cancellation Policy', 'footer'),
('footer.links.cancellation_policy', 'de', 'Stornierungsrichtlinien', 'footer'),
('footer.links.cancellation_policy', 'fr', 'Politique d''Annulation', 'footer'),
('footer.links.cancellation_policy', 'it', 'Politica di Cancellazione', 'footer'),
('footer.links.cancellation_policy', 'es', 'Política de Cancelación', 'footer'),
('footer.links.cancellation_policy', 'ru', 'Политика отмены', 'footer'),

('footer.links.gdpr', 'en', 'GDPR', 'footer'),
('footer.links.gdpr', 'de', 'DSGVO', 'footer'),
('footer.links.gdpr', 'fr', 'RGPD', 'footer'),
('footer.links.gdpr', 'it', 'GDPR', 'footer'),
('footer.links.gdpr', 'es', 'RGPD', 'footer'),
('footer.links.gdpr', 'ru', 'GDPR', 'footer'),

('footer.copyright', 'en', '© 2025 Garda Racing Yacht Club. All rights reserved.', 'footer'),
('footer.copyright', 'de', '© 2025 Garda Racing Yacht Club. Alle Rechte vorbehalten.', 'footer'),
('footer.copyright', 'fr', '© 2025 Garda Racing Yacht Club. Tous droits réservés.', 'footer'),
('footer.copyright', 'it', '© 2025 Garda Racing Yacht Club. Tutti i diritti riservati.', 'footer'),
('footer.copyright', 'es', '© 2025 Garda Racing Yacht Club. Todos los derechos reservados.', 'footer'),
('footer.copyright', 'ru', '© 2025 Garda Racing Yacht Club. Все права защищены.', 'footer')

ON CONFLICT (key, language_code) DO NOTHING;